/**
 * BIAIF i18n — Internationalisation module
 * Exposes window.BIAIFi18n with t(), applyDOM(), setLang(), getLang(), detectBrowserLang()
 * Supported languages: fr, en, es, de, it, pt, nl (fallback: fr)
 */
(function (window) {
  'use strict';

  var SUPPORTED = ['fr', 'en', 'es', 'de', 'it', 'pt', 'nl'];
  var _lang = 'fr';

  // ── Translations ────────────────────────────────────────────────────────────
  var TRANSLATIONS = {
    'settings.title':                   { fr: 'Réglages',                                               en: 'Settings',                                         es: 'Ajustes',                                          de: 'Einstellungen',                                    it: 'Impostazioni',                                     pt: 'Configurações',                                    nl: 'Instellingen' },
    'settings.voice.title':             { fr: 'Reconnaissance vocale',                                  en: 'Voice recognition',                                 es: 'Reconocimiento de voz',                            de: 'Spracherkennung',                                  it: 'Riconoscimento vocale',                            pt: 'Reconhecimento de voz',                            nl: 'Spraakherkenning' },
    'settings.voice.lang_label':        { fr: 'Langue',                                                 en: 'Language',                                          es: 'Idioma',                                           de: 'Sprache',                                          it: 'Lingua',                                           pt: 'Idioma',                                           nl: 'Taal' },
    'settings.voice.mic_label':         { fr: 'Microphone',                                             en: 'Microphone',                                        es: 'Micrófono',                                        de: 'Mikrofon',                                         it: 'Microfono',                                        pt: 'Microfone',                                        nl: 'Microfoon' },
    'settings.voice.mic_default':       { fr: 'Système par défaut',                                     en: 'System default',                                    es: 'Sistema predeterminado',                           de: 'Systemstandard',                                   it: 'Predefinito',                                      pt: 'Padrão do sistema',                                nl: 'Systeemstandaard' },
    'settings.voice.test':              { fr: 'Tester',                                                 en: 'Test',                                              es: 'Probar',                                           de: 'Testen',                                           it: 'Testa',                                            pt: 'Testar',                                           nl: 'Testen' },
    'settings.voice.refresh':           { fr: 'Actualiser',                                             en: 'Refresh',                                           es: 'Actualizar',                                       de: 'Aktualisieren',                                    it: 'Aggiorna',                                         pt: 'Atualizar',                                        nl: 'Vernieuwen' },
    'settings.export.title':            { fr: "Boutons d'export",                                       en: 'Export buttons',                                    es: 'Botones de exportación',                           de: 'Export-Schaltflächen',                             it: 'Pulsanti di esportazione',                         pt: 'Botões de exportação',                             nl: 'Exportknoppen' },
    'settings.export.desc':             { fr: 'Choisissez quels boutons afficher sur chaque demande.',  en: 'Choose which buttons to show on each request.',     es: 'Elige qué botones mostrar en cada solicitud.',     de: 'Wähle, welche Schaltflächen bei jeder Anfrage angezeigt werden.', it: 'Scegli quali pulsanti mostrare su ogni richiesta.', pt: 'Escolha quais botões exibir em cada solicitação.', nl: 'Kies welke knoppen bij elk verzoek worden weergegeven.' },
    'settings.export.inject_hint':      { fr: 'Injection directe dans Claude.ai',                       en: 'Direct injection into Claude.ai',                   es: 'Inyección directa en Claude.ai',                   de: 'Direkte Injektion in Claude.ai',                   it: 'Iniezione diretta in Claude.ai',                   pt: 'Injeção direta no Claude.ai',                      nl: 'Directe injectie in Claude.ai' },
    'settings.export.vscode_hint':      { fr: 'Bridge local → Claude Code CLI',                         en: 'Bridge local → Claude Code CLI',                    es: 'Bridge local → Claude Code CLI',                   de: 'Bridge local → Claude Code CLI',                   it: 'Bridge local → Claude Code CLI',                   pt: 'Bridge local → Claude Code CLI',                   nl: 'Bridge local → Claude Code CLI' },
    'settings.export.copilot_hint':     { fr: 'GitHub Copilot Chat',                                    en: 'GitHub Copilot Chat',                               es: 'GitHub Copilot Chat',                              de: 'GitHub Copilot Chat',                              it: 'GitHub Copilot Chat',                              pt: 'GitHub Copilot Chat',                              nl: 'GitHub Copilot Chat' },
    'settings.export.copy_hint':        { fr: 'Prompt dans le presse-papier',                           en: 'Prompt to clipboard',                               es: 'Prompt al portapapeles',                           de: 'Prompt in die Zwischenablage',                     it: 'Prompt negli appunti',                             pt: 'Prompt para área de transferência',                nl: 'Prompt naar klembord' },
    'settings.export.download_hint':    { fr: 'Télécharger Markdown + captures',                        en: 'Download Markdown + screenshots',                   es: 'Descargar Markdown + capturas',                    de: 'Markdown + Screenshots herunterladen',              it: 'Scarica Markdown + screenshot',                    pt: 'Baixar Markdown + capturas',                       nl: 'Markdown + schermafbeeldingen downloaden' },
    'settings.display.title':           { fr: 'Affichage',                                              en: 'Display',                                           es: 'Visualización',                                    de: 'Anzeige',                                          it: 'Visualizzazione',                                  pt: 'Exibição',                                         nl: 'Weergave' },
    'settings.display.font_label':      { fr: 'Taille du texte des demandes',                           en: 'Request text size',                                 es: 'Tamaño del texto',                                 de: 'Textgröße der Anfragen',                           it: 'Dimensione del testo',                             pt: 'Tamanho do texto',                                 nl: 'Tekstgrootte' },
    'settings.ui_lang.title':           { fr: "Langue de l'interface",                                  en: 'Interface language',                                es: 'Idioma de la interfaz',                            de: 'Schnittstellensprache',                            it: "Lingua dell'interfaccia",                          pt: 'Idioma da interface',                              nl: 'Interfacetaal' },
    'settings.help.title':              { fr: 'Aide',                                                   en: 'Help',                                              es: 'Ayuda',                                            de: 'Hilfe',                                            it: 'Aiuto',                                            pt: 'Ajuda',                                            nl: 'Help' },
    'settings.help.review_guide':       { fr: 'Revoir le guide de démarrage',                           en: 'Review the getting started guide',                  es: 'Revisar la guía de inicio',                        de: 'Einführungshandbuch anzeigen',                     it: 'Rivedi la guida introduttiva',                     pt: 'Revisar o guia de início',                         nl: 'Startgids bekijken' },
    'settings.help.shortcuts':          { fr: 'Raccourcis clavier',                                     en: 'Keyboard shortcuts',                                es: 'Atajos de teclado',                                de: 'Tastenkürzel',                                     it: 'Scorciatoie da tastiera',                          pt: 'Atalhos de teclado',                               nl: 'Sneltoetsen' },
    'btn.inject':                       { fr: 'Injecter',                                               en: 'Inject',                                            es: 'Inyectar',                                         de: 'Injizieren',                                       it: 'Inietta',                                          pt: 'Injetar',                                          nl: 'Injecteren' },
    'btn.vscode':                       { fr: 'VS Code',                                                en: 'VS Code',                                           es: 'VS Code',                                          de: 'VS Code',                                          it: 'VS Code',                                          pt: 'VS Code',                                          nl: 'VS Code' },
    'btn.copilot':                      { fr: 'Copilot',                                                en: 'Copilot',                                           es: 'Copilot',                                          de: 'Copilot',                                          it: 'Copilot',                                          pt: 'Copilot',                                          nl: 'Copilot' },
    'btn.copy':                         { fr: 'Copier',                                                 en: 'Copy',                                              es: 'Copiar',                                           de: 'Kopieren',                                         it: 'Copia',                                            pt: 'Copiar',                                           nl: 'Kopiëren' },
    'btn.download':                     { fr: '.MD',                                                    en: '.MD',                                               es: '.MD',                                              de: '.MD',                                              it: '.MD',                                              pt: '.MD',                                              nl: '.MD' },
    'tools.mic':                        { fr: 'Micro',                                                  en: 'Mic',                                               es: 'Micro',                                            de: 'Mikro',                                            it: 'Micro',                                            pt: 'Micro',                                            nl: 'Micro' },
    'tools.picker':                     { fr: 'Sélecteur',                                              en: 'Picker',                                            es: 'Selector',                                         de: 'Auswahl',                                          it: 'Selettore',                                        pt: 'Seletor',                                          nl: 'Kiezer' },
    'tools.capture':                    { fr: 'Capture',                                                en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnahme',                                         it: 'Cattura',                                          pt: 'Captura',                                          nl: 'Opname' },
    'tools.file':                       { fr: 'Fichier',                                                en: 'File',                                              es: 'Archivo',                                          de: 'Datei',                                            it: 'File',                                             pt: 'Arquivo',                                          nl: 'Bestand' },
    'tools.errors':                     { fr: 'Erreurs',                                                en: 'Errors',                                            es: 'Errores',                                          de: 'Fehler',                                           it: 'Errori',                                           pt: 'Erros',                                            nl: 'Fouten' },
    'capture.visible':                  { fr: 'Visible',                                                en: 'Visible',                                           es: 'Visible',                                          de: 'Visible',                                          it: 'Visible',                                          pt: 'Visible',                                          nl: 'Visible' },
    'capture.selection':                { fr: 'Sélection',                                              en: 'Selection',                                         es: 'Selección',                                        de: 'Auswahl',                                          it: 'Selezione',                                        pt: 'Seleção',                                          nl: 'Selectie' },
    'capture.element':                  { fr: 'Élément',                                                en: 'Element',                                           es: 'Elemento',                                         de: 'Element',                                          it: 'Elemento',                                         pt: 'Elemento',                                         nl: 'Element' },
    'capture.fullpage':                 { fr: 'Page entière',                                           en: 'Full page',                                         es: 'Página completa',                                  de: 'Ganze Seite',                                      it: 'Pagina intera',                                    pt: 'Página inteira',                                   nl: 'Volledige pagina' },
    'hero.speak':                       { fr: 'Parlez',                                                 en: 'Speak',                                             es: 'Habla',                                            de: 'Sprechen',                                         it: 'Parla',                                            pt: 'Fale',                                             nl: 'Spreek' },
    'hero.target':                      { fr: 'Ciblez',                                                 en: 'Target',                                            es: 'Apunta',                                           de: 'Ziel',                                             it: 'Punta',                                            pt: 'Mire',                                             nl: 'Richt' },
    'hero.capture':                     { fr: 'Capturez',                                               en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnehmen',                                        it: 'Cattura',                                          pt: 'Capture',                                          nl: 'Leg vast' },
    'hero.imagine':                     { fr: 'Imaginez',                                               en: 'Imagine',                                           es: 'Imagina',                                          de: 'Vorstellen',                                       it: 'Immagina',                                         pt: 'Imagine',                                          nl: 'Stel je voor' },
    'hero.tagline':                     { fr: 'Vos besoins, vos idées, vos retours —',                  en: 'Your needs, ideas, and feedback —',                 es: 'Tus necesidades, ideas y comentarios —',           de: 'Ihre Anforderungen, Ideen und Feedback —',         it: 'I tuoi bisogni, idee e feedback —',                pt: 'Suas necessidades, ideias e feedback —',           nl: 'Uw behoeften, ideeën en feedback —' },
    'hero.tagline_em':                  { fr: 'transmis naturellement à votre IA.',                     en: 'naturally transmitted to your AI.',                 es: 'transmitidos naturalmente a tu IA.',               de: 'natürlich an Ihre KI übermittelt.',                it: 'trasmessi naturalmente alla tua IA.',               pt: 'transmitidos naturalmente para sua IA.',           nl: 'naturlijk doorgegeven aan uw AI.' },
    'segments.title':                   { fr: 'Historique',                                             en: 'History',                                           es: 'Historial',                                        de: 'Verlauf',                                          it: 'Cronologia',                                       pt: 'Histórico',                                        nl: 'Geschiedenis' },
    'segments.search_placeholder':      { fr: "Rechercher dans l'historique…",                          en: 'Search history…',                                   es: 'Buscar en el historial…',                          de: 'Verlauf durchsuchen…',                             it: 'Cerca nella cronologia…',                          pt: 'Pesquisar no histórico…',                          nl: 'Geschiedenis doorzoeken…' },
    'segments.empty':                   { fr: 'Aucune demande pour le moment',                          en: 'No requests yet',                                   es: 'Sin solicitudes por el momento',                   de: 'Noch keine Anfragen',                              it: 'Nessuna richiesta al momento',                     pt: 'Nenhuma solicitação por enquanto',                 nl: 'Nog geen verzoeken' },
    'footer.clear':                     { fr: 'Vider',                                                  en: 'Clear',                                             es: 'Vaciar',                                           de: 'Leeren',                                           it: 'Svuota',                                           pt: 'Limpar',                                           nl: 'Leeg' },
    'footer.copy':                      { fr: 'Copier',                                                 en: 'Copy',                                              es: 'Copiar',                                           de: 'Kopieren',                                         it: 'Copia',                                            pt: 'Copiar',                                           nl: 'Kopiëren' },
    'session.start':                    { fr: 'Démarrer',                                               en: 'Start',                                             es: 'Iniciar',                                          de: 'Starten',                                          it: 'Avvia',                                            pt: 'Iniciar',                                          nl: 'Starten' },
    'session.next':                     { fr: 'Suivant →',                                              en: 'Next →',                                            es: 'Siguiente →',                                      de: 'Weiter →',                                         it: 'Avanti →',                                         pt: 'Próximo →',                                        nl: 'Volgende →' },
    'session.new_segment':              { fr: 'Nouveau segment',                                        en: 'New segment',                                       es: 'Nuevo segmento',                                   de: 'Neues Segment',                                    it: 'Nuovo segmento',                                   pt: 'Novo segmento',                                    nl: 'Nieuw segment' },
    'session.finish':                   { fr: 'Terminer',                                               en: 'Finish',                                            es: 'Finalizar',                                        de: 'Abschließen',                                      it: 'Fine',                                             pt: 'Finalizar',                                        nl: 'Voltooien' },
    'demande.title':                    { fr: 'Demande en cours',                                       en: 'Current request',                                   es: 'Solicitud actual',                                 de: 'Aktuelle Anfrage',                                 it: 'Richiesta corrente',                               pt: 'Solicitação atual',                                nl: 'Huidige aanvraag' },
    'demande.refs':                     { fr: '{n} réf',                                                en: '{n} ref',                                           es: '{n} ref',                                          de: '{n} Ref.',                                         it: '{n} rif',                                          pt: '{n} ref',                                          nl: '{n} ref' },
    'demande.placeholder':              { fr: 'Parlez ou tapez votre demande. Cliquez sur un élément ou capturez pour insérer une référence.', en: 'Speak or type your request. Click an element or capture to insert a reference.', es: 'Habla o escribe tu solicitud. Haz clic en un elemento o captura para insertar una referencia.', de: 'Sprechen oder tippen Sie Ihre Anfrage. Klicken Sie auf ein Element oder nehmen Sie es auf.', it: 'Parla o digita la tua richiesta. Fai clic su un elemento o cattura per inserire un riferimento.', pt: 'Fale ou digite sua solicitação. Clique em um elemento ou capture para inserir uma referência.', nl: 'Spreek of typ uw verzoek. Klik op een element of leg het vast om een referentie in te voegen.' },
    'modal.reload.title':               { fr: 'Recharger la page',                                      en: 'Reload page',                                       es: 'Recargar la página',                               de: 'Seite neu laden',                                  it: 'Ricarica la pagina',                               pt: 'Recarregar a página',                              nl: 'Pagina herladen' },
    'modal.reload.desc':                { fr: "L'extension n'est pas active sur cet onglet — la page doit être rechargée pour utiliser le sélecteur et les captures.", en: 'The extension is not active on this tab — the page must be reloaded to use the picker and captures.', es: 'La extensión no está activa en esta pestaña — la página debe recargarse para usar el selector y las capturas.', de: 'Die Erweiterung ist auf diesem Tab nicht aktiv — die Seite muss neu geladen werden.', it: "L'estensione non è attiva su questa scheda — la pagina deve essere ricaricata.", pt: 'A extensão não está ativa nesta aba — a página precisa ser recarregada.', nl: 'De extensie is niet actief op dit tabblad — de pagina moet herladen worden.' },
    'modal.reload.confirm':             { fr: "Recharger l'onglet",                                     en: 'Reload tab',                                        es: 'Recargar pestaña',                                 de: 'Tab neu laden',                                    it: 'Ricarica scheda',                                  pt: 'Recarregar aba',                                   nl: 'Tabblad herladen' },
    'modal.reload.dismiss':             { fr: 'Plus tard',                                              en: 'Later',                                             es: 'Más tarde',                                        de: 'Später',                                           it: 'Più tardi',                                        pt: 'Mais tarde',                                       nl: 'Later' },
    'logs.clear':                       { fr: 'Effacer',                                                en: 'Clear',                                             es: 'Borrar',                                           de: 'Löschen',                                          it: 'Cancella',                                         pt: 'Limpar',                                           nl: 'Wissen' },
    'wizard.nav.skip':                  { fr: 'Passer',                                                 en: 'Skip',                                              es: 'Omitir',                                           de: 'Überspringen',                                     it: 'Salta',                                            pt: 'Pular',                                            nl: 'Overslaan' },
    'wizard.nav.back':                  { fr: '← Retour',                                               en: '← Back',                                            es: '← Volver',                                         de: '← Zurück',                                         it: '← Indietro',                                       pt: '← Voltar',                                         nl: '← Terug' },
    'wizard.nav.next':                  { fr: 'Suivant →',                                              en: 'Next →',                                            es: 'Siguiente →',                                      de: 'Weiter →',                                         it: 'Avanti →',                                         pt: 'Próximo →',                                        nl: 'Volgende →' },
    'wizard.nav.done':                  { fr: '✓ Commencer',                                            en: '✓ Start',                                           es: '✓ Comenzar',                                       de: '✓ Beginnen',                                       it: '✓ Inizia',                                         pt: '✓ Começar',                                        nl: '✓ Starten' },
    'wizard.welcome.title':             { fr: 'Bienvenue dans',                                         en: 'Welcome to',                                        es: 'Bienvenido a',                                     de: 'Willkommen bei',                                   it: 'Benvenuto in',                                     pt: 'Bem-vindo ao',                                     nl: 'Welkom bij' },
    'wizard.welcome.sub':               { fr: 'BI · Chrome · AI · Feedback',                            en: 'BI · Chrome · AI · Feedback',                       es: 'BI · Chrome · AI · Feedback',                      de: 'BI · Chrome · AI · Feedback',                      it: 'BI · Chrome · AI · Feedback',                      pt: 'BI · Chrome · AI · Feedback',                      nl: 'BI · Chrome · AI · Feedback' },
    'wizard.welcome.desc':              { fr: "Capturez vos idées, bugs et retours directement depuis le navigateur et transmettez-les à votre IA — avec texte, captures d'écran et contexte HTML.", en: 'Capture your ideas, bugs, and feedback directly from the browser and send them to your AI — with text, screenshots, and HTML context.', es: 'Captura tus ideas, bugs y comentarios directamente desde el navegador y envíalos a tu IA — con texto, capturas de pantalla y contexto HTML.', de: 'Erfasse deine Ideen, Bugs und Feedback direkt im Browser und sende sie an deine KI — mit Text, Screenshots und HTML-Kontext.', it: 'Cattura idee, bug e feedback direttamente dal browser e inviàli alla tua IA — con testo, screenshot e contesto HTML.', pt: 'Capture suas ideias, bugs e feedback diretamente do navegador e envie para sua IA — com texto, capturas de tela e contexto HTML.', nl: 'Leg uw ideeën, bugs en feedback vast rechtstreeks vanuit de browser en stuur ze naar uw AI — met tekst, schermafbeeldingen en HTML-context.' },
    'wizard.flow.title':                { fr: 'Comment ça marche',                                      en: 'How it works',                                      es: 'Cómo funciona',                                    de: 'Wie es funktioniert',                              it: 'Come funziona',                                    pt: 'Como funciona',                                    nl: 'Hoe het werkt' },
    'wizard.flow.step1_title':          { fr: 'Démarrez',                                               en: 'Start',                                             es: 'Inicia',                                           de: 'Starten',                                          it: 'Avvia',                                            pt: 'Inicie',                                           nl: 'Starten' },
    'wizard.flow.step1_desc':           { fr: 'Cliquez "Démarrer" — micro et sélecteur s\'activent',    en: 'Click "Start" — mic and picker activate',           es: 'Haz clic en "Iniciar" — se activan el micrófono y el selector', de: 'Klicke auf "Starten" — Mikrofon und Auswahl werden aktiviert', it: 'Fai clic su "Avvia" — il microfono e il selettore si attivano', pt: 'Clique em "Iniciar" — microfone e seletor são ativados', nl: 'Klik op "Starten" — microfoon en kiezer worden geactiveerd' },
    'wizard.flow.step2_title':          { fr: 'Exprimez-vous',                                          en: 'Express yourself',                                  es: 'Exprésate',                                        de: 'Ausdrücken',                                       it: 'Esprimi',                                          pt: 'Expresse-se',                                      nl: 'Druk je uit' },
    'wizard.flow.step2_desc':           { fr: 'Parlez ou tapez votre instruction naturellement',        en: 'Speak or type your instruction naturally',          es: 'Habla o escribe tu instrucción naturalmente',      de: 'Spreche oder tippe deine Anweisung natürlich',     it: 'Parla o digita la tua istruzione naturalmente',    pt: 'Fale ou escreva sua instrução naturalmente',       nl: 'Spreek of typ uw instructie op een natuurlijke manier' },
    'wizard.flow.step3_title':          { fr: 'Ciblez & capturez',                                      en: 'Target & capture',                                  es: 'Apunta y captura',                                 de: 'Zielen & aufnehmen',                               it: 'Punta e cattura',                                  pt: 'Mire e capture',                                   nl: 'Richt & leg vast' },
    'wizard.flow.step3_desc':           { fr: 'Pointez un élément, prenez une capture ou ajoutez une erreur JS', en: 'Point to an element, take a screenshot or add a JS error', es: 'Señala un elemento, toma una captura o añade un error JS', de: 'Zeige auf ein Element, mache einen Screenshot oder füge einen JS-Fehler hinzu', it: 'Punta a un elemento, fai uno screenshot o aggiungi un errore JS', pt: 'Aponte para um elemento, tire uma captura ou adicione um erro JS', nl: 'Wijs naar een element, maak een screenshot of voeg een JS-fout toe' },
    'wizard.flow.step4_title':          { fr: 'Exportez',                                               en: 'Export',                                            es: 'Exporta',                                          de: 'Exportieren',                                      it: 'Esporta',                                          pt: 'Exporte',                                          nl: 'Exporteer' },
    'wizard.flow.step4_desc':           { fr: 'Injectez dans votre IA ou copiez le prompt formaté',    en: 'Inject into your AI or copy the formatted prompt',  es: 'Inyecta en tu IA o copia el prompt formateado',    de: 'Injiziere in deine KI oder kopiere den formatierten Prompt', it: 'Inietta nella tua IA o copia il prompt formattato', pt: 'Injete na sua IA ou copie o prompt formatado',    nl: 'Injecteer in uw AI of kopieer de geformatteerde prompt' },
    'wizard.tools.title':               { fr: 'Outils de capture',                                      en: 'Capture tools',                                     es: 'Herramientas de captura',                          de: 'Aufnahme-Tools',                                   it: 'Strumenti di cattura',                             pt: 'Ferramentas de captura',                           nl: 'Opname-tools' },
    'wizard.tools.mic_label':           { fr: 'Micro',                                                  en: 'Mic',                                               es: 'Micro',                                            de: 'Mikro',                                            it: 'Micro',                                            pt: 'Micro',                                            nl: 'Micro' },
    'wizard.tools.mic_desc':            { fr: 'Dictée vocale multilingue',                              en: 'Multilingual voice dictation',                      es: 'Dictado de voz multilingüe',                       de: 'Mehrsprachige Spracheingabe',                       it: 'Dettatura vocale multilingue',                     pt: 'Ditado de voz multilíngue',                        nl: 'Meertalige spraakinvoer' },
    'wizard.tools.picker_label':        { fr: 'Sélecteur',                                              en: 'Picker',                                            es: 'Selector',                                         de: 'Auswahl',                                          it: 'Selettore',                                        pt: 'Seletor',                                          nl: 'Kiezer' },
    'wizard.tools.picker_desc':         { fr: 'Pointez un élément → selector, tag, texte, HTML',        en: 'Point to an element → selector, tag, text, HTML',   es: 'Señala un elemento → selector, etiqueta, texto, HTML', de: 'Zeige auf ein Element → Selektor, Tag, Text, HTML', it: 'Punta a un elemento → selector, tag, testo, HTML', pt: 'Aponte para um elemento → seletor, tag, texto, HTML', nl: 'Wijs naar een element → selector, tag, tekst, HTML' },
    'wizard.tools.capture_label':       { fr: 'Capture',                                                en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnahme',                                         it: 'Cattura',                                          pt: 'Captura',                                          nl: 'Opname' },
    'wizard.tools.capture_desc':        { fr: '4 modes : visible, sélection, élément, pleine page',     en: '4 modes: visible, selection, element, full page',   es: '4 modos: visible, selección, elemento, página completa', de: '4 Modi: sichtbar, Auswahl, Element, ganze Seite',  it: '4 modalità: visibile, selezione, elemento, pagina intera', pt: '4 modos: visível, seleção, elemento, página inteira', nl: '4 modi: zichtbaar, selectie, element, volledige pagina' },
    'wizard.tools.file_label':          { fr: 'Fichier',                                                en: 'File',                                              es: 'Archivo',                                          de: 'Datei',                                            it: 'File',                                             pt: 'Arquivo',                                          nl: 'Bestand' },
    'wizard.tools.file_desc':           { fr: 'Importez une image ou glissez-déposez',                  en: 'Import an image or drag and drop',                  es: 'Importa una imagen o arrastra y suelta',           de: 'Importiere ein Bild oder ziehe es per Drag & Drop', it: 'Importa un\'immagine o trascina e rilascia',        pt: 'Importe uma imagem ou arraste e solte',            nl: 'Importeer een afbeelding of sleep en zet neer' },
    'wizard.tools.errors_label':        { fr: 'Erreurs JS',                                             en: 'JS Errors',                                         es: 'Errores JS',                                       de: 'JS-Fehler',                                        it: 'Errori JS',                                        pt: 'Erros JS',                                         nl: 'JS-fouten' },
    'wizard.tools.errors_desc':         { fr: 'Capture les erreurs console de la page active',          en: 'Captures console errors from the active page',      es: 'Captura los errores de consola de la página activa', de: 'Erfasst Konsolenfehler der aktiven Seite',         it: 'Cattura gli errori della console della pagina attiva', pt: 'Captura erros do console da página ativa',         nl: 'Legt consolefouten van de actieve pagina vast' },
    'wizard.lang.title':                { fr: 'Langue de reconnaissance vocale',                        en: 'Voice recognition language',                        es: 'Idioma de reconocimiento de voz',                  de: 'Spracheingabesprache',                             it: 'Lingua di riconoscimento vocale',                  pt: 'Idioma de reconhecimento de voz',                  nl: 'Spraakherkenninginstaal' },
    'wizard.lang.desc':                 { fr: 'Quelle langue utiliserez-vous principalement pour dicter vos instructions ?', en: 'What language will you mainly use to dictate your instructions?', es: '¿Qué idioma usarás principalmente para dictar tus instrucciones?', de: 'Welche Sprache wirst du hauptsächlich zum Diktieren verwenden?', it: 'Quale lingua userai principalmente per dettare le istruzioni?', pt: 'Qual idioma você usará principalmente para ditar suas instruções?', nl: 'Welke taal gebruik je voornamelijk om je instructies te dicteren?' },
    'wizard.lang.hint':                 { fr: 'Modifiable à tout moment dans ⚙ Réglages → Reconnaissance vocale.',         en: 'Can be changed at any time in ⚙ Settings → Voice Recognition.',    es: 'Se puede cambiar en cualquier momento en ⚙ Ajustes → Reconocimiento de voz.',  de: 'Jederzeit änderbar unter ⚙ Einstellungen → Spracherkennung.',             it: 'Modificabile in qualsiasi momento in ⚙ Impostazioni → Riconoscimento vocale.',  pt: 'Pode ser alterado a qualquer momento em ⚙ Configurações → Reconhecimento de voz.',  nl: 'Op elk moment te wijzigen via ⚙ Instellingen → Spraakherkenning.' },
    'wizard.export.title':              { fr: "Boutons d'export",                                       en: 'Export buttons',                                    es: 'Botones de exportación',                           de: 'Export-Schaltflächen',                             it: 'Pulsanti di esportazione',                         pt: 'Botões de exportação',                             nl: 'Exportknoppen' },
    'wizard.export.desc':               { fr: 'Activez uniquement les outils que vous utilisez. Vous pourrez changer ça dans ⚙ Réglages.', en: 'Only enable the tools you use. You can change this in ⚙ Settings.', es: 'Activa solo las herramientas que usas. Puedes cambiar esto en ⚙ Ajustes.', de: 'Aktiviere nur die Werkzeuge, die du verwendest. Du kannst dies unter ⚙ Einstellungen ändern.', it: 'Abilita solo gli strumenti che usi. Puoi cambiare questo in ⚙ Impostazioni.', pt: 'Ative apenas as ferramentas que você usa. Você pode mudar isso em ⚙ Configurações.', nl: 'Activeer alleen de tools die je gebruikt. Je kunt dit wijzigen in ⚙ Instellingen.' },
    'wizard.export.inject_desc':        { fr: 'Injection directe dans Claude.ai (texte + images)',      en: 'Direct injection into Claude.ai (text + images)',   es: 'Inyección directa en Claude.ai (texto + imágenes)', de: 'Direkte Injektion in Claude.ai (Text + Bilder)',   it: 'Iniezione diretta in Claude.ai (testo + immagini)', pt: 'Injeção direta no Claude.ai (texto + imagens)',   nl: 'Directe injectie in Claude.ai (tekst + afbeeldingen)' },
    'wizard.export.vscode_desc':        { fr: 'Bridge local → terminal Claude Code CLI',                en: 'Local bridge → Claude Code CLI terminal',           es: 'Puente local → terminal Claude Code CLI',          de: 'Lokale Brücke → Claude Code CLI-Terminal',         it: 'Bridge locale → terminale Claude Code CLI',        pt: 'Bridge local → terminal Claude Code CLI',          nl: 'Lokale brug → Claude Code CLI-terminal' },
    'wizard.export.copilot_desc':       { fr: 'GitHub Copilot Chat (texte + fichiers joints)',           en: 'GitHub Copilot Chat (text + attached files)',       es: 'GitHub Copilot Chat (texto + archivos adjuntos)',  de: 'GitHub Copilot Chat (Text + angehängte Dateien)',  it: 'GitHub Copilot Chat (testo + file allegati)',       pt: 'GitHub Copilot Chat (texto + arquivos anexados)',  nl: 'GitHub Copilot Chat (tekst + bijgevoegde bestanden)' },
    'wizard.export.copy_desc':          { fr: 'Prompt Markdown dans le presse-papier',                  en: 'Markdown prompt to clipboard',                      es: 'Prompt Markdown al portapapeles',                  de: 'Markdown-Prompt in die Zwischenablage',            it: 'Prompt Markdown negli appunti',                    pt: 'Prompt Markdown para área de transferência',       nl: 'Markdown-prompt naar klembord' },
    'wizard.export.download_desc':      { fr: 'Archive Markdown + captures PNG',                        en: 'Markdown archive + PNG screenshots',                es: 'Archivo Markdown + capturas PNG',                  de: 'Markdown-Archiv + PNG-Screenshots',                it: 'Archivio Markdown + screenshot PNG',               pt: 'Arquivo Markdown + capturas PNG',                  nl: 'Markdown-archief + PNG-schermafbeeldingen' },
    'wizard.ready.title':               { fr: 'Vous êtes prêt !',                                       en: "You're ready!",                                     es: '¡Estás listo!',                                    de: 'Sie sind bereit!',                                 it: 'Sei pronto!',                                      pt: 'Você está pronto!',                                nl: 'U bent klaar!' },
    'wizard.ready.step1':               { fr: 'Cliquez <strong>Démarrer</strong> pour activer la session', en: 'Click <strong>Start</strong> to activate the session', es: 'Haz clic en <strong>Iniciar</strong> para activar la sesión', de: 'Klicke auf <strong>Starten</strong> um die Sitzung zu aktivieren', it: 'Fai clic su <strong>Avvia</strong> per attivare la sessione', pt: 'Clique em <strong>Iniciar</strong> para ativar a sessão', nl: 'Klik op <strong>Starten</strong> om de sessie te activeren' },
    'wizard.ready.step2':               { fr: 'Configurez à nouveau via <strong>⚙ Réglages</strong> à tout moment', en: 'Reconfigure at any time via <strong>⚙ Settings</strong>', es: 'Vuelve a configurar en cualquier momento con <strong>⚙ Ajustes</strong>', de: 'Jederzeit neu konfigurieren über <strong>⚙ Einstellungen</strong>', it: 'Riconfigura in qualsiasi momento tramite <strong>⚙ Impostazioni</strong>', pt: 'Reconfigure a qualquer momento via <strong>⚙ Configurações</strong>', nl: 'Herconfigureer op elk moment via <strong>⚙ Instellingen</strong>' },
    'wizard.ready.step3':               { fr: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copier', en: '<code>Alt+Shift+M</code> mic &nbsp;·&nbsp; <code>Alt+Shift+C</code> copy', es: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copiar', de: '<code>Alt+Shift+M</code> Mikro &nbsp;·&nbsp; <code>Alt+Shift+C</code> kopieren', it: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copia', pt: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copiar', nl: '<code>Alt+Shift+M</code> microfoon &nbsp;·&nbsp; <code>Alt+Shift+C</code> kopiëren' },
    'wizard.ready.step4':               { fr: 'Retrouvez ce guide : <strong>⚙ Réglages → Revoir le guide</strong>', en: 'Find this guide again: <strong>⚙ Settings → Review guide</strong>', es: 'Encuentra esta guía: <strong>⚙ Ajustes → Revisar guía</strong>', de: 'Finde diese Anleitung wieder: <strong>⚙ Einstellungen → Anleitung ansehen</strong>', it: 'Ritrova questa guida: <strong>⚙ Impostazioni → Rivedi la guida</strong>', pt: 'Encontre este guia: <strong>⚙ Configurações → Revisar guia</strong>', nl: 'Vind deze gids terug: <strong>⚙ Instellingen → Gids bekijken</strong>' },
    'wizard.ready.lang_label':          { fr: 'Langue',                                                 en: 'Language',                                          es: 'Idioma',                                           de: 'Sprache',                                          it: 'Lingua',                                           pt: 'Idioma',                                           nl: 'Taal' },
    'wizard.ready.buttons_label':       { fr: 'Boutons actifs',                                         en: 'Active buttons',                                    es: 'Botones activos',                                  de: 'Aktive Schaltflächen',                             it: 'Pulsanti attivi',                                  pt: 'Botões ativos',                                    nl: 'Actieve knoppen' },
    'toast.ready':                      { fr: 'Prêt.',                                                  en: 'Ready.',                                            es: 'Listo.',                                           de: 'Bereit.',                                          it: 'Pronto.',                                          pt: 'Pronto.',                                          nl: 'Klaar.' },
    'toast.cleared':                    { fr: 'Tout effacé.',                                           en: 'All cleared.',                                      es: 'Todo borrado.',                                    de: 'Alles gelöscht.',                                  it: 'Tutto cancellato.',                                pt: 'Tudo apagado.',                                    nl: 'Alles gewist.' },
    'toast.nothing_to_undo':            { fr: 'Rien à annuler.',                                        en: 'Nothing to undo.',                                  es: 'Nada que deshacer.',                               de: 'Nichts rückgängig zu machen.',                     it: 'Niente da annullare.',                             pt: 'Nada a desfazer.',                                 nl: 'Niets om ongedaan te maken.' },
    'toast.undone':                     { fr: 'Action annulée.',                                        en: 'Action undone.',                                    es: 'Acción deshecha.',                                 de: 'Aktion rückgängig gemacht.',                       it: 'Azione annullata.',                                pt: 'Ação desfeita.',                                   nl: 'Actie ongedaan gemaakt.' },
  };

  // ── API ─────────────────────────────────────────────────────────────────────

  function t(key) {
    var entry = TRANSLATIONS[key];
    if (!entry) return key;
    return entry[_lang] || entry['fr'] || key;
  }

  function getLang() {
    return _lang;
  }

  function detectBrowserLang() {
    var nav = (navigator.language || navigator.userLanguage || 'fr').toLowerCase();
    var base = nav.split('-')[0];
    if (SUPPORTED.indexOf(base) !== -1) return base;
    return 'fr';
  }

  function setLang(lang) {
    if (SUPPORTED.indexOf(lang) === -1) lang = 'fr';
    _lang = lang;
    // Update <html lang="">
    document.documentElement.setAttribute('lang', lang);
    // Update active button in #sp-lang-grid
    var grid = document.getElementById('sp-lang-grid');
    if (grid) {
      grid.querySelectorAll('[data-lang]').forEach(function (btn) {
        btn.classList.toggle('is-active', btn.dataset.lang === lang);
      });
    }
    applyDOM();
  }

  function applyDOM() {
    // data-i18n: textContent
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (key) el.textContent = t(key);
    });
    // data-i18n-html: innerHTML
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (key) el.innerHTML = t(key);
    });
    // data-i18n-placeholder: placeholder attribute
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder');
      if (key) el.setAttribute('placeholder', t(key));
    });
  }

  // ── Export ──────────────────────────────────────────────────────────────────
  window.BIAIFi18n = {
    t: t,
    getLang: getLang,
    setLang: setLang,
    applyDOM: applyDOM,
    detectBrowserLang: detectBrowserLang,
  };

})(window);
