/**
 * BIAIF i18n — Internationalisation module
 * Exposes window.BIAIFi18n with t(), applyDOM(), setLang(), getLang(), detectBrowserLang()
 * Supported languages: fr, en, es, de, it, pt, nl (fallback: fr)
 *
 * t(key, vars) supports {placeholder} substitution from `vars` object.
 */
(function (window) {
  'use strict';

  var SUPPORTED = ['fr', 'en', 'es', 'de', 'it', 'pt', 'nl'];
  var _lang = 'fr';

  // ── Translations ────────────────────────────────────────────────────────────
  var TRANSLATIONS = {
    // ===================== STATIC UI =====================
    'settings.title':                   { fr: 'Réglages',                                               en: 'Settings',                                         es: 'Ajustes',                                          de: 'Einstellungen',                                    it: 'Impostazioni',                                     pt: 'Configurações',                                    nl: 'Instellingen' },
    'settings.voice.title':             { fr: 'Reconnaissance vocale',                                  en: 'Voice recognition',                                 es: 'Reconocimiento de voz',                            de: 'Spracherkennung',                                  it: 'Riconoscimento vocale',                            pt: 'Reconhecimento de voz',                            nl: 'Spraakherkenning' },
    'settings.voice.lang_label':        { fr: 'Langue',                                                 en: 'Language',                                          es: 'Idioma',                                           de: 'Sprache',                                          it: 'Lingua',                                           pt: 'Idioma',                                           nl: 'Taal' },
    'settings.voice.mic_label':         { fr: 'Microphone',                                             en: 'Microphone',                                        es: 'Micrófono',                                        de: 'Mikrofon',                                         it: 'Microfono',                                        pt: 'Microfone',                                        nl: 'Microfoon' },
    'settings.voice.mic_default':       { fr: 'Système par défaut',                                     en: 'System default',                                    es: 'Sistema predeterminado',                           de: 'Systemstandard',                                   it: 'Predefinito',                                      pt: 'Padrão do sistema',                                nl: 'Systeemstandaard' },
    'settings.voice.test':              { fr: 'Tester',                                                 en: 'Test',                                              es: 'Probar',                                           de: 'Testen',                                           it: 'Testa',                                            pt: 'Testar',                                           nl: 'Testen' },
    'settings.voice.refresh':           { fr: 'Actualiser',                                             en: 'Refresh',                                           es: 'Actualizar',                                       de: 'Aktualisieren',                                    it: 'Aggiorna',                                         pt: 'Atualizar',                                        nl: 'Vernieuwen' },
    'settings.export.title':            { fr: "Boutons d'export",                                       en: 'Export buttons',                                    es: 'Botones de exportación',                           de: 'Export-Schaltflächen',                             it: 'Pulsanti di esportazione',                         pt: 'Botões de exportação',                             nl: 'Exportknoppen' },
    'settings.export.desc':             { fr: 'Choisissez quels boutons afficher sur chaque demande.',  en: 'Choose which buttons to show on each request.',     es: 'Elige qué botones mostrar en cada solicitud.',     de: 'Wähle, welche Schaltflächen bei jeder Anfrage angezeigt werden.', it: 'Scegli quali pulsanti mostrare su ogni richiesta.', pt: 'Escolha quais botões exibir em cada solicitação.', nl: 'Kies welke knoppen bij elk verzoek worden weergegeven.' },
    'settings.export.inject_hint':      { fr: 'Injection directe dans Claude.ai',                       en: 'Direct injection into Claude.ai',                   es: 'Inyección directa en Claude.ai',                   de: 'Direkte Injektion in Claude.ai',                   it: 'Iniezione diretta in Claude.ai',                   pt: 'Injeção direta no Claude.ai',                      nl: 'Directe injectie in Claude.ai' },
    'settings.export.vscode_hint':      { fr: 'Bridge local → Claude Code CLI',                         en: 'Local bridge → Claude Code CLI',                    es: 'Bridge local → Claude Code CLI',                   de: 'Lokale Bridge → Claude Code CLI',                  it: 'Bridge locale → Claude Code CLI',                  pt: 'Bridge local → Claude Code CLI',                   nl: 'Lokale bridge → Claude Code CLI' },
    'settings.export.copilot_hint':     { fr: 'GitHub Copilot Chat',                                    en: 'GitHub Copilot Chat',                               es: 'GitHub Copilot Chat',                              de: 'GitHub Copilot Chat',                              it: 'GitHub Copilot Chat',                              pt: 'GitHub Copilot Chat',                              nl: 'GitHub Copilot Chat' },
    'settings.export.copy_hint':        { fr: 'Prompt dans le presse-papier',                           en: 'Prompt to clipboard',                               es: 'Prompt al portapapeles',                           de: 'Prompt in die Zwischenablage',                     it: 'Prompt negli appunti',                             pt: 'Prompt para área de transferência',                nl: 'Prompt naar klembord' },
    'settings.export.download_hint':    { fr: 'Télécharger Markdown + captures',                        en: 'Download Markdown + screenshots',                   es: 'Descargar Markdown + capturas',                    de: 'Markdown + Screenshots herunterladen',              it: 'Scarica Markdown + screenshot',                    pt: 'Baixar Markdown + capturas',                       nl: 'Markdown + schermafbeeldingen downloaden' },
    'settings.export.other_ai':         { fr: 'Autres IA (copie + ouverture)',                          en: 'Other AIs (copy + open)',                           es: 'Otras IA (copiar + abrir)',                        de: 'Andere KIs (kopieren + öffnen)',                   it: 'Altre IA (copia + apri)',                          pt: 'Outras IAs (copiar + abrir)',                      nl: 'Andere AIs (kopiëren + openen)' },
    'settings.export.other_ai_hint':    { fr: 'Copie le prompt et ouvre l\'IA dans un nouvel onglet',    en: 'Copies the prompt and opens the AI in a new tab',   es: 'Copia el prompt y abre la IA en una pestaña',      de: 'Kopiert den Prompt und öffnet die KI in neuem Tab', it: 'Copia il prompt e apre l\'IA in una nuova scheda', pt: 'Copia o prompt e abre a IA em uma nova aba',       nl: 'Kopieert de prompt en opent de AI in een nieuw tabblad' },
    'settings.display.title':           { fr: 'Affichage',                                              en: 'Display',                                           es: 'Visualización',                                    de: 'Anzeige',                                          it: 'Visualizzazione',                                  pt: 'Exibição',                                         nl: 'Weergave' },
    'settings.display.font_label':      { fr: 'Taille du texte des demandes',                           en: 'Request text size',                                 es: 'Tamaño del texto',                                 de: 'Textgröße der Anfragen',                           it: 'Dimensione del testo',                             pt: 'Tamanho do texto',                                 nl: 'Tekstgrootte' },
    'settings.ui_lang.title':           { fr: "Langue de l'interface",                                  en: 'Interface language',                                es: 'Idioma de la interfaz',                            de: 'Schnittstellensprache',                            it: "Lingua dell'interfaccia",                          pt: 'Idioma da interface',                              nl: 'Interfacetaal' },
    'settings.help.title':              { fr: 'Aide',                                                   en: 'Help',                                              es: 'Ayuda',                                            de: 'Hilfe',                                            it: 'Aiuto',                                            pt: 'Ajuda',                                            nl: 'Help' },
    'settings.help.review_guide':       { fr: 'Revoir le guide de démarrage',                           en: 'Review the getting started guide',                  es: 'Revisar la guía de inicio',                        de: 'Einführungshandbuch anzeigen',                     it: 'Rivedi la guida introduttiva',                     pt: 'Revisar o guia de início',                         nl: 'Startgids bekijken' },
    'settings.help.shortcuts':          { fr: 'Raccourcis clavier',                                     en: 'Keyboard shortcuts',                                es: 'Atajos de teclado',                                de: 'Tastenkürzel',                                     it: 'Scorciatoie da tastiera',                          pt: 'Atalhos de teclado',                               nl: 'Sneltoetsen' },

    'btn.inject':                       { fr: 'Injecter',                                               en: 'Inject',                                            es: 'Inyectar',                                         de: 'Injizieren',                                       it: 'Inietta',                                          pt: 'Injetar',                                          nl: 'Injecteren' },
    'btn.vscode':                       { fr: 'VS-Code Terminal',                                       en: 'VS-Code Terminal',                                  es: 'VS-Code Terminal',                                 de: 'VS-Code Terminal',                                 it: 'VS-Code Terminal',                                 pt: 'VS-Code Terminal',                                 nl: 'VS-Code Terminal' },
    'btn.copilot':                      { fr: 'VS-Code GH for Copilot',                                 en: 'VS-Code GH for Copilot',                            es: 'VS-Code GH for Copilot',                           de: 'VS-Code GH for Copilot',                           it: 'VS-Code GH for Copilot',                           pt: 'VS-Code GH for Copilot',                           nl: 'VS-Code GH for Copilot' },
    'btn.copy':                         { fr: 'Copier',                                                 en: 'Copy',                                              es: 'Copiar',                                           de: 'Kopieren',                                         it: 'Copia',                                            pt: 'Copiar',                                           nl: 'Kopiëren' },
    'btn.download':                     { fr: '.MD',                                                    en: '.MD',                                               es: '.MD',                                              de: '.MD',                                              it: '.MD',                                              pt: '.MD',                                              nl: '.MD' },
    'btn.claude_online':                { fr: 'Claude.ai',                                              en: 'Claude.ai',                                         es: 'Claude.ai',                                        de: 'Claude.ai',                                        it: 'Claude.ai',                                        pt: 'Claude.ai',                                        nl: 'Claude.ai' },
    'btn.chatgpt':                      { fr: 'ChatGPT',                                                en: 'ChatGPT',                                           es: 'ChatGPT',                                          de: 'ChatGPT',                                          it: 'ChatGPT',                                          pt: 'ChatGPT',                                          nl: 'ChatGPT' },
    'btn.gemini':                       { fr: 'Gemini',                                                 en: 'Gemini',                                            es: 'Gemini',                                           de: 'Gemini',                                           it: 'Gemini',                                           pt: 'Gemini',                                           nl: 'Gemini' },
    'btn.perplexity':                   { fr: 'Perplexity',                                             en: 'Perplexity',                                        es: 'Perplexity',                                       de: 'Perplexity',                                       it: 'Perplexity',                                       pt: 'Perplexity',                                       nl: 'Perplexity' },
    'btn.grok':                         { fr: 'Grok',                                                   en: 'Grok',                                              es: 'Grok',                                             de: 'Grok',                                             it: 'Grok',                                             pt: 'Grok',                                             nl: 'Grok' },
    'btn.lechat':                       { fr: 'Le Chat',                                                en: 'Le Chat',                                           es: 'Le Chat',                                          de: 'Le Chat',                                          it: 'Le Chat',                                          pt: 'Le Chat',                                          nl: 'Le Chat' },
    'btn.deepseek':                     { fr: 'DeepSeek',                                               en: 'DeepSeek',                                          es: 'DeepSeek',                                         de: 'DeepSeek',                                         it: 'DeepSeek',                                         pt: 'DeepSeek',                                         nl: 'DeepSeek' },

    'tools.mic':                        { fr: 'Micro',                                                  en: 'Mic',                                               es: 'Micro',                                            de: 'Mikro',                                            it: 'Micro',                                            pt: 'Micro',                                            nl: 'Micro' },
    'tools.picker':                     { fr: 'Sélecteur',                                              en: 'Picker',                                            es: 'Selector',                                         de: 'Auswahl',                                          it: 'Selettore',                                        pt: 'Seletor',                                          nl: 'Kiezer' },
    'tools.picker_active':              { fr: 'Picker actif',                                           en: 'Picker active',                                     es: 'Selector activo',                                  de: 'Auswahl aktiv',                                    it: 'Selettore attivo',                                 pt: 'Seletor ativo',                                    nl: 'Kiezer actief' },
    'tools.capture':                    { fr: 'Capture',                                                en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnahme',                                         it: 'Cattura',                                          pt: 'Captura',                                          nl: 'Opname' },
    'tools.file':                       { fr: 'Fichier',                                                en: 'File',                                              es: 'Archivo',                                          de: 'Datei',                                            it: 'File',                                             pt: 'Arquivo',                                          nl: 'Bestand' },
    'tools.errors':                     { fr: 'Erreurs',                                                en: 'Errors',                                            es: 'Errores',                                          de: 'Fehler',                                           it: 'Errori',                                           pt: 'Erros',                                            nl: 'Fouten' },
    'capture.visible':                  { fr: 'Visible',                                                en: 'Visible',                                           es: 'Visible',                                          de: 'Sichtbar',                                         it: 'Visibile',                                         pt: 'Visível',                                          nl: 'Zichtbaar' },
    'capture.selection':                { fr: 'Sélection',                                              en: 'Selection',                                         es: 'Selección',                                        de: 'Auswahl',                                          it: 'Selezione',                                        pt: 'Seleção',                                          nl: 'Selectie' },
    'capture.element':                  { fr: 'Élément',                                                en: 'Element',                                           es: 'Elemento',                                         de: 'Element',                                          it: 'Elemento',                                         pt: 'Elemento',                                         nl: 'Element' },
    'capture.fullpage':                 { fr: 'Page entière',                                           en: 'Full page',                                         es: 'Página completa',                                  de: 'Ganze Seite',                                      it: 'Pagina intera',                                    pt: 'Página inteira',                                   nl: 'Volledige pagina' },
    'hero.speak':                       { fr: 'Parlez',                                                 en: 'Speak',                                             es: 'Habla',                                            de: 'Sprechen',                                         it: 'Parla',                                            pt: 'Fale',                                             nl: 'Spreek' },
    'hero.target':                      { fr: 'Ciblez',                                                 en: 'Target',                                            es: 'Apunta',                                           de: 'Ziel',                                             it: 'Punta',                                            pt: 'Mire',                                             nl: 'Richt' },
    'hero.capture':                     { fr: 'Capturez',                                               en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnehmen',                                        it: 'Cattura',                                          pt: 'Capture',                                          nl: 'Leg vast' },
    'hero.imagine':                     { fr: 'Imaginez',                                               en: 'Imagine',                                           es: 'Imagina',                                          de: 'Vorstellen',                                       it: 'Immagina',                                         pt: 'Imagine',                                          nl: 'Stel je voor' },
    'hero.tagline':                     { fr: 'Vos besoins, vos idées, vos retours —',                  en: 'Your needs, ideas, and feedback —',                 es: 'Tus necesidades, ideas y comentarios —',           de: 'Ihre Anforderungen, Ideen und Feedback —',         it: 'I tuoi bisogni, idee e feedback —',                pt: 'Suas necessidades, ideias e feedback —',           nl: 'Uw behoeften, ideeën en feedback —' },
    'hero.tagline_em':                  { fr: 'transmis naturellement à votre IA.',                     en: 'naturally transmitted to your AI.',                 es: 'transmitidos naturalmente a tu IA.',               de: 'natürlich an Ihre KI übermittelt.',                it: 'trasmessi naturalmente alla tua IA.',               pt: 'transmitidos naturalmente para sua IA.',           nl: 'naturlijk doorgegeven aan uw AI.' },
    'segments.title':                   { fr: 'Historique',                                             en: 'History',                                           es: 'Historial',                                        de: 'Verlauf',                                          it: 'Cronologia',                                       pt: 'Histórico',                                        nl: 'Geschiedenis' },
    'segments.search_placeholder':      { fr: "Rechercher dans l'historique…",                          en: 'Search history…',                                   es: 'Buscar en el historial…',                          de: 'Verlauf durchsuchen…',                             it: 'Cerca nella cronologia…',                          pt: 'Pesquisar no histórico…',                          nl: 'Geschiedenis doorzoeken…' },
    'segments.empty':                   { fr: 'Aucune demande pour le moment',                          en: 'No requests yet',                                   es: 'Sin solicitudes por el momento',                   de: 'Noch keine Anfragen',                              it: 'Nessuna richiesta al momento',                     pt: 'Nenhuma solicitação por enquanto',                 nl: 'Nog geen verzoeken' },
    'segments.no_results':              { fr: 'Aucun résultat pour cette recherche',                    en: 'No results for this search',                        es: 'Sin resultados para esta búsqueda',                de: 'Keine Ergebnisse für diese Suche',                 it: 'Nessun risultato per questa ricerca',              pt: 'Sem resultados para esta busca',                   nl: 'Geen resultaten voor deze zoekopdracht' },
    'segments.ref_singular':            { fr: '{n} réf',                                                en: '{n} ref',                                           es: '{n} ref',                                          de: '{n} Ref.',                                         it: '{n} rif',                                          pt: '{n} ref',                                          nl: '{n} ref' },
    'segments.ref_plural':              { fr: '{n} réfs',                                               en: '{n} refs',                                          es: '{n} refs',                                         de: '{n} Refs',                                         it: '{n} rif',                                          pt: '{n} refs',                                         nl: '{n} refs' },
    'footer.clear':                     { fr: 'Vider',                                                  en: 'Clear',                                             es: 'Vaciar',                                           de: 'Leeren',                                           it: 'Svuota',                                           pt: 'Limpar',                                           nl: 'Leeg' },
    'footer.copy':                      { fr: 'Copier',                                                 en: 'Copy',                                              es: 'Copiar',                                           de: 'Kopieren',                                         it: 'Copia',                                            pt: 'Copiar',                                           nl: 'Kopiëren' },
    'session.start':                    { fr: 'Démarrer',                                               en: 'Start',                                             es: 'Iniciar',                                          de: 'Starten',                                          it: 'Avvia',                                            pt: 'Iniciar',                                          nl: 'Starten' },
    'session.next':                     { fr: 'Suivant →',                                              en: 'Next →',                                            es: 'Siguiente →',                                      de: 'Weiter →',                                         it: 'Avanti →',                                         pt: 'Próximo →',                                        nl: 'Volgende →' },
    'session.new_segment':              { fr: 'Nouveau segment',                                        en: 'New segment',                                       es: 'Nuevo segmento',                                   de: 'Neues Segment',                                    it: 'Nuovo segmento',                                   pt: 'Novo segmento',                                    nl: 'Nieuw segment' },
    'session.finish':                   { fr: 'Terminer',                                               en: 'Finish',                                            es: 'Finalizar',                                        de: 'Abschließen',                                      it: 'Fine',                                             pt: 'Finalizar',                                        nl: 'Voltooien' },
    'demande.title':                    { fr: 'Demande en cours',                                       en: 'Current request',                                   es: 'Solicitud actual',                                 de: 'Aktuelle Anfrage',                                 it: 'Richiesta corrente',                               pt: 'Solicitação atual',                                nl: 'Huidige aanvraag' },
    'demande.refs':                     { fr: '{n} réf',                                                en: '{n} ref',                                           es: '{n} ref',                                          de: '{n} Ref.',                                         it: '{n} rif',                                          pt: '{n} ref',                                          nl: '{n} ref' },
    'demande.placeholder':              { fr: 'Parlez ou tapez votre demande. Cliquez sur un élément ou capturez pour insérer une référence.', en: 'Speak or type your request. Click an element or capture to insert a reference.', es: 'Habla o escribe tu solicitud. Haz clic en un elemento o captura para insertar una referencia.', de: 'Sprechen oder tippen Sie Ihre Anfrage. Klicken Sie auf ein Element oder nehmen Sie es auf.', it: 'Parla o digita la tua richiesta. Fai clic su un elemento o cattura per inserire un riferimento.', pt: 'Fale ou digite sua solicitação. Clique em um elemento ou capture para inserir uma referência.', nl: 'Spreek of typ uw verzoek. Klik op een element of leg het vast om een referentie in te voegen.' },
    'modal.reload.title':               { fr: 'Recharger la page',                                      en: 'Reload page',                                       es: 'Recargar la página',                               de: 'Seite neu laden',                                  it: 'Ricarica la pagina',                               pt: 'Recarregar a página',                              nl: 'Pagina herladen' },
    'modal.reload.desc':                { fr: "L'extension n'est pas active sur cet onglet — la page doit être rechargée pour utiliser le sélecteur et les captures.", en: 'The extension is not active on this tab — the page must be reloaded to use the picker and captures.', es: 'La extensión no está activa en esta pestaña — la página debe recargarse para usar el selector y las capturas.', de: 'Die Erweiterung ist auf diesem Tab nicht aktiv — die Seite muss neu geladen werden.', it: "L'estensione non è attiva su questa scheda — la pagina deve essere ricaricata.", pt: 'A extensão não está ativa nesta aba — a página precisa ser recarregada.', nl: 'De extensie is niet actief op dit tabblad — de pagina moet herladen worden.' },
    'modal.reload.confirm':             { fr: "Recharger l'onglet",                                     en: 'Reload tab',                                        es: 'Recargar pestaña',                                 de: 'Tab neu laden',                                    it: 'Ricarica scheda',                                  pt: 'Recarregar aba',                                   nl: 'Tabblad herladen' },
    'modal.reload.dismiss':             { fr: 'Plus tard',                                              en: 'Later',                                             es: 'Más tarde',                                        de: 'Später',                                           it: 'Più tardi',                                        pt: 'Mais tarde',                                       nl: 'Later' },
    'logs.clear':                       { fr: 'Effacer',                                                en: 'Clear',                                             es: 'Borrar',                                           de: 'Löschen',                                          it: 'Cancella',                                         pt: 'Limpar',                                           nl: 'Wissen' },

    // ===================== WIZARD =====================
    'wizard.nav.skip':                  { fr: 'Passer',                                                 en: 'Skip',                                              es: 'Omitir',                                           de: 'Überspringen',                                     it: 'Salta',                                            pt: 'Pular',                                            nl: 'Overslaan' },
    'wizard.nav.back':                  { fr: '← Retour',                                               en: '← Back',                                            es: '← Volver',                                         de: '← Zurück',                                         it: '← Indietro',                                       pt: '← Voltar',                                         nl: '← Terug' },
    'wizard.nav.next':                  { fr: 'Suivant →',                                              en: 'Next →',                                            es: 'Siguiente →',                                      de: 'Weiter →',                                         it: 'Avanti →',                                         pt: 'Próximo →',                                        nl: 'Volgende →' },
    'wizard.nav.done':                  { fr: '✓ Commencer',                                            en: '✓ Start',                                           es: '✓ Comenzar',                                       de: '✓ Beginnen',                                       it: '✓ Inizia',                                         pt: '✓ Começar',                                        nl: '✓ Starten' },
    'wizard.welcome.title':             { fr: 'Bienvenue dans',                                         en: 'Welcome to',                                        es: 'Bienvenido a',                                     de: 'Willkommen bei',                                   it: 'Benvenuto in',                                     pt: 'Bem-vindo ao',                                     nl: 'Welkom bij' },
    'wizard.welcome.sub':               { fr: 'BI · Chrome · AI · Feedback',                            en: 'BI · Chrome · AI · Feedback',                       es: 'BI · Chrome · AI · Feedback',                      de: 'BI · Chrome · AI · Feedback',                      it: 'BI · Chrome · AI · Feedback',                      pt: 'BI · Chrome · AI · Feedback',                      nl: 'BI · Chrome · AI · Feedback' },
    'wizard.welcome.desc':              { fr: "Capturez vos idées, bugs et retours directement depuis le navigateur et transmettez-les à votre IA — avec texte, captures d'écran et contexte HTML.", en: 'Capture your ideas, bugs, and feedback directly from the browser and send them to your AI — with text, screenshots, and HTML context.', es: 'Captura tus ideas, bugs y comentarios directamente desde el navegador y envíalos a tu IA — con texto, capturas de pantalla y contexto HTML.', de: 'Erfasse deine Ideen, Bugs und Feedback direkt im Browser und sende sie an deine KI — mit Text, Screenshots und HTML-Kontext.', it: 'Cattura idee, bug e feedback direttamente dal browser e inviàli alla tua IA — con testo, screenshot e contesto HTML.', pt: 'Capture suas ideias, bugs e feedback diretamente do navegador e envie para sua IA — com texto, capturas de tela e contexto HTML.', nl: 'Leg uw ideeën, bugs en feedback vast rechtstreeks vanuit de browser en stuur ze naar uw AI — met tekst, schermafbeeldingen en HTML-context.' },
    'wizard.flow.title':                { fr: 'Comment ça marche',                                      en: 'How it works',                                      es: 'Cómo funciona',                                    de: 'Wie es funktioniert',                              it: 'Come funziona',                                    pt: 'Como funciona',                                    nl: 'Hoe het werkt' },
    'wizard.flow.step1_title':          { fr: 'Démarrez',                                               en: 'Start',                                             es: 'Inicia',                                           de: 'Starten',                                          it: 'Avvia',                                            pt: 'Inicie',                                           nl: 'Starten' },
    'wizard.flow.step1_desc':           { fr: 'Cliquez "Démarrer" — micro et sélecteur s\'activent',    en: 'Click "Start" — mic and picker activate',           es: 'Haz clic en "Iniciar" — se activan el micrófono y el selector', de: 'Klicke auf "Starten" — Mikrofon und Auswahl werden aktiviert', it: 'Fai clic su "Avvia" — il microfono e il selettore si attivano', pt: 'Clique em "Iniciar" — microfone e seletor são ativados', nl: 'Klik op "Starten" — microfoon en kiezer worden geactiveerd' },
    'wizard.flow.step2_title':          { fr: 'Exprimez-vous',                                          en: 'Express yourself',                                  es: 'Exprésate',                                        de: 'Ausdrücken',                                       it: 'Esprimi',                                          pt: 'Expresse-se',                                      nl: 'Druk je uit' },
    'wizard.flow.step2_desc':           { fr: 'Parlez ou tapez votre instruction naturellement',        en: 'Speak or type your instruction naturally',          es: 'Habla o escribe tu instrucción naturalmente',      de: 'Spreche oder tippe deine Anweisung natürlich',     it: 'Parla o digita la tua istruzione naturalmente',    pt: 'Fale ou escreva sua instrução naturalmente',       nl: 'Spreek of typ uw instructie op een natuurlijke manier' },
    'wizard.flow.step3_title':          { fr: 'Ciblez & capturez',                                      en: 'Target & capture',                                  es: 'Apunta y captura',                                 de: 'Zielen & aufnehmen',                               it: 'Punta e cattura',                                  pt: 'Mire e capture',                                   nl: 'Richt & leg vast' },
    'wizard.flow.step3_desc':           { fr: 'Pointez un élément, prenez une capture ou ajoutez une erreur JS', en: 'Point to an element, take a screenshot or add a JS error', es: 'Señala un elemento, toma una captura o añade un error JS', de: 'Zeige auf ein Element, mache einen Screenshot oder füge einen JS-Fehler hinzu', it: 'Punta a un elemento, fai uno screenshot o aggiungi un errore JS', pt: 'Aponte para um elemento, tire uma captura ou adicione um erro JS', nl: 'Wijs naar een element, maak een screenshot of voeg een JS-fout toe' },
    'wizard.flow.step4_title':          { fr: 'Exportez',                                               en: 'Export',                                            es: 'Exporta',                                          de: 'Exportieren',                                      it: 'Esporta',                                          pt: 'Exporte',                                          nl: 'Exporteer' },
    'wizard.flow.step4_desc':           { fr: 'Injectez dans votre IA ou copiez le prompt formaté',    en: 'Inject into your AI or copy the formatted prompt',  es: 'Inyecta en tu IA o copia el prompt formateado',    de: 'Injiziere in deine KI oder kopiere den formatierten Prompt', it: 'Inietta nella tua IA o copia il prompt formattato', pt: 'Injete na sua IA ou copie o prompt formatado',    nl: 'Injecteer in uw AI of kopieer de geformatteerde prompt' },
    'wizard.tools.title':               { fr: 'Outils de capture',                                      en: 'Capture tools',                                     es: 'Herramientas de captura',                          de: 'Aufnahme-Tools',                                   it: 'Strumenti di cattura',                             pt: 'Ferramentas de captura',                           nl: 'Opname-tools' },
    'wizard.tools.mic_label':           { fr: 'Micro',                                                  en: 'Mic',                                               es: 'Micro',                                            de: 'Mikro',                                            it: 'Micro',                                            pt: 'Micro',                                            nl: 'Micro' },
    'wizard.tools.mic_desc':            { fr: 'Dictée vocale multilingue',                              en: 'Multilingual voice dictation',                      es: 'Dictado de voz multilingüe',                       de: 'Mehrsprachige Spracheingabe',                       it: 'Dettatura vocale multilingue',                     pt: 'Ditado de voz multilíngue',                        nl: 'Meertalige spraakinvoer' },
    'wizard.tools.picker_label':        { fr: 'Sélecteur',                                              en: 'Picker',                                            es: 'Selector',                                         de: 'Auswahl',                                          it: 'Selettore',                                        pt: 'Seletor',                                          nl: 'Kiezer' },
    'wizard.tools.picker_desc':         { fr: 'Pointez un élément → selector, tag, texte, HTML',        en: 'Point to an element → selector, tag, text, HTML',   es: 'Señala un elemento → selector, etiqueta, texto, HTML', de: 'Zeige auf ein Element → Selektor, Tag, Text, HTML', it: 'Punta a un elemento → selector, tag, testo, HTML', pt: 'Aponte para um elemento → seletor, tag, texto, HTML', nl: 'Wijs naar een element → selector, tag, tekst, HTML' },
    'wizard.tools.capture_label':       { fr: 'Capture',                                                en: 'Capture',                                           es: 'Captura',                                          de: 'Aufnahme',                                         it: 'Cattura',                                          pt: 'Captura',                                          nl: 'Opname' },
    'wizard.tools.capture_desc':        { fr: '4 modes : visible, sélection, élément, pleine page',     en: '4 modes: visible, selection, element, full page',   es: '4 modos: visible, selección, elemento, página completa', de: '4 Modi: sichtbar, Auswahl, Element, ganze Seite',  it: '4 modalità: visibile, selezione, elemento, pagina intera', pt: '4 modos: visível, seleção, elemento, página inteira', nl: '4 modi: zichtbaar, selectie, element, volledige pagina' },
    'wizard.tools.file_label':          { fr: 'Fichier',                                                en: 'File',                                              es: 'Archivo',                                          de: 'Datei',                                            it: 'File',                                             pt: 'Arquivo',                                          nl: 'Bestand' },
    'wizard.tools.file_desc':           { fr: 'Importez une image ou glissez-déposez',                  en: 'Import an image or drag and drop',                  es: 'Importa una imagen o arrastra y suelta',           de: 'Importiere ein Bild oder ziehe es per Drag & Drop', it: 'Importa un\'immagine o trascina e rilascia',        pt: 'Importe uma imagem ou arraste e solte',            nl: 'Importeer een afbeelding of sleep en zet neer' },
    'wizard.tools.errors_label':        { fr: 'Erreurs JS',                                             en: 'JS Errors',                                         es: 'Errores JS',                                       de: 'JS-Fehler',                                        it: 'Errori JS',                                        pt: 'Erros JS',                                         nl: 'JS-fouten' },
    'wizard.tools.errors_desc':         { fr: 'Capture les erreurs console de la page active',          en: 'Captures console errors from the active page',      es: 'Captura los errores de consola de la página activa', de: 'Erfasst Konsolenfehler der aktiven Seite',         it: 'Cattura gli errori della console della pagina attiva', pt: 'Captura erros do console da página ativa',         nl: 'Legt consolefouten van de actieve pagina vast' },
    'wizard.lang.title':                { fr: 'Langue de reconnaissance vocale',                        en: 'Voice recognition language',                        es: 'Idioma de reconocimiento de voz',                  de: 'Spracheingabesprache',                             it: 'Lingua di riconoscimento vocale',                  pt: 'Idioma de reconhecimento de voz',                  nl: 'Spraakherkenninginstaal' },
    'wizard.lang.desc':                 { fr: 'Quelle langue utiliserez-vous principalement pour dicter vos instructions ?', en: 'What language will you mainly use to dictate your instructions?', es: '¿Qué idioma usarás principalmente para dictar tus instrucciones?', de: 'Welche Sprache wirst du hauptsächlich zum Diktieren verwenden?', it: 'Quale lingua userai principalmente per dettare le istruzioni?', pt: 'Qual idioma você usará principalmente para ditar suas instruções?', nl: 'Welke taal gebruik je voornamelijk om je instructies te dicteren?' },
    'wizard.lang.hint':                 { fr: 'Modifiable à tout moment dans ⚙ Réglages → Reconnaissance vocale.',         en: 'Can be changed at any time in ⚙ Settings → Voice Recognition.',    es: 'Se puede cambiar en cualquier momento en ⚙ Ajustes → Reconocimiento de voz.',  de: 'Jederzeit änderbar unter ⚙ Einstellungen → Spracherkennung.',             it: 'Modificabile in qualsiasi momento in ⚙ Impostazioni → Riconoscimento vocale.',  pt: 'Pode ser alterado a qualquer momento em ⚙ Configurações → Reconhecimento de voz.',  nl: 'Op elk moment te wijzigen via ⚙ Instellingen → Spraakherkenning.' },
    'wizard.export.title':              { fr: "Boutons d'export",                                       en: 'Export buttons',                                    es: 'Botones de exportación',                           de: 'Export-Schaltflächen',                             it: 'Pulsanti di esportazione',                         pt: 'Botões de exportação',                             nl: 'Exportknoppen' },
    'wizard.export.desc':               { fr: 'Activez uniquement les outils que vous utilisez. Vous pourrez changer ça dans ⚙ Réglages.', en: 'Only enable the tools you use. You can change this in ⚙ Settings.', es: 'Activa solo las herramientas que usas. Puedes cambiar esto en ⚙ Ajustes.', de: 'Aktiviere nur die Werkzeuge, die du verwendest. Du kannst dies unter ⚙ Einstellungen ändern.', it: 'Abilita solo gli strumenti che usi. Puoi cambiare questo in ⚙ Impostazioni.', pt: 'Ative apenas as ferramentas que você usa. Você pode mudar isso em ⚙ Configurações.', nl: 'Activeer alleen de tools die je gebruikt. Je kunt dit wijzigen in ⚙ Instellingen.' },
    'wizard.export.inject_desc':        { fr: 'Injection directe dans Claude.ai (texte + images)',      en: 'Direct injection into Claude.ai (text + images)',   es: 'Inyección directa en Claude.ai (texto + imágenes)', de: 'Direkte Injektion in Claude.ai (Text + Bilder)',   it: 'Iniezione diretta in Claude.ai (testo + immagini)', pt: 'Injeção direta no Claude.ai (texto + imagens)',   nl: 'Directe injectie in Claude.ai (tekst + afbeeldingen)' },
    'wizard.export.vscode_desc':        { fr: 'Bridge local → terminal Claude Code CLI',                en: 'Local bridge → Claude Code CLI terminal',           es: 'Puente local → terminal Claude Code CLI',          de: 'Lokale Brücke → Claude Code CLI-Terminal',         it: 'Bridge locale → terminale Claude Code CLI',        pt: 'Bridge local → terminal Claude Code CLI',          nl: 'Lokale brug → Claude Code CLI-terminal' },
    'wizard.export.copilot_desc':       { fr: 'GitHub Copilot Chat (texte + fichiers joints)',           en: 'GitHub Copilot Chat (text + attached files)',       es: 'GitHub Copilot Chat (texto + archivos adjuntos)',  de: 'GitHub Copilot Chat (Text + angehängte Dateien)',  it: 'GitHub Copilot Chat (testo + file allegati)',       pt: 'GitHub Copilot Chat (texto + arquivos anexados)',  nl: 'GitHub Copilot Chat (tekst + bijgevoegde bestanden)' },
    'wizard.export.copy_desc':          { fr: 'Prompt Markdown dans le presse-papier',                  en: 'Markdown prompt to clipboard',                      es: 'Prompt Markdown al portapapeles',                  de: 'Markdown-Prompt in die Zwischenablage',            it: 'Prompt Markdown negli appunti',                    pt: 'Prompt Markdown para área de transferência',       nl: 'Markdown-prompt naar klembord' },
    'wizard.export.download_desc':      { fr: 'Archive Markdown + captures PNG',                        en: 'Markdown archive + PNG screenshots',                es: 'Archivo Markdown + capturas PNG',                  de: 'Markdown-Archiv + PNG-Screenshots',                it: 'Archivio Markdown + screenshot PNG',               pt: 'Arquivo Markdown + capturas PNG',                  nl: 'Markdown-archief + PNG-schermafbeeldingen' },
    'wizard.export.online_desc':        { fr: 'Copie le prompt et ouvre {name} dans un nouvel onglet', en: 'Copies the prompt and opens {name} in a new tab',   es: 'Copia el prompt y abre {name} en una pestaña',     de: 'Kopiert den Prompt und öffnet {name} in neuem Tab', it: 'Copia il prompt e apre {name} in una nuova scheda', pt: 'Copia o prompt e abre {name} em uma nova aba',     nl: 'Kopieert de prompt en opent {name} in een nieuw tabblad' },
    'wizard.ready.title':               { fr: 'Vous êtes prêt !',                                       en: "You're ready!",                                     es: '¡Estás listo!',                                    de: 'Sie sind bereit!',                                 it: 'Sei pronto!',                                      pt: 'Você está pronto!',                                nl: 'U bent klaar!' },
    'wizard.ready.step1':               { fr: 'Cliquez <strong>Démarrer</strong> pour activer la session', en: 'Click <strong>Start</strong> to activate the session', es: 'Haz clic en <strong>Iniciar</strong> para activar la sesión', de: 'Klicke auf <strong>Starten</strong> um die Sitzung zu aktivieren', it: 'Fai clic su <strong>Avvia</strong> per attivare la sessione', pt: 'Clique em <strong>Iniciar</strong> para ativar a sessão', nl: 'Klik op <strong>Starten</strong> om de sessie te activeren' },
    'wizard.ready.step2':               { fr: 'Configurez à nouveau via <strong>⚙ Réglages</strong> à tout moment', en: 'Reconfigure at any time via <strong>⚙ Settings</strong>', es: 'Vuelve a configurar en cualquier momento con <strong>⚙ Ajustes</strong>', de: 'Jederzeit neu konfigurieren über <strong>⚙ Einstellungen</strong>', it: 'Riconfigura in qualsiasi momento tramite <strong>⚙ Impostazioni</strong>', pt: 'Reconfigure a qualquer momento via <strong>⚙ Configurações</strong>', nl: 'Herconfigureer op elk moment via <strong>⚙ Instellingen</strong>' },
    'wizard.ready.step3':               { fr: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copier', en: '<code>Alt+Shift+M</code> mic &nbsp;·&nbsp; <code>Alt+Shift+C</code> copy', es: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copiar', de: '<code>Alt+Shift+M</code> Mikro &nbsp;·&nbsp; <code>Alt+Shift+C</code> kopieren', it: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copia', pt: '<code>Alt+Shift+M</code> micro &nbsp;·&nbsp; <code>Alt+Shift+C</code> copiar', nl: '<code>Alt+Shift+M</code> microfoon &nbsp;·&nbsp; <code>Alt+Shift+C</code> kopiëren' },
    'wizard.ready.step4':               { fr: 'Retrouvez ce guide : <strong>⚙ Réglages → Revoir le guide</strong>', en: 'Find this guide again: <strong>⚙ Settings → Review guide</strong>', es: 'Encuentra esta guía: <strong>⚙ Ajustes → Revisar guía</strong>', de: 'Finde diese Anleitung wieder: <strong>⚙ Einstellungen → Anleitung ansehen</strong>', it: 'Ritrova questa guida: <strong>⚙ Impostazioni → Rivedi la guida</strong>', pt: 'Encontre este guia: <strong>⚙ Configurações → Revisar guia</strong>', nl: 'Vind deze gids terug: <strong>⚙ Instellingen → Gids bekijken</strong>' },
    'wizard.ready.lang_label':          { fr: 'Langue',                                                 en: 'Language',                                          es: 'Idioma',                                           de: 'Sprache',                                          it: 'Lingua',                                           pt: 'Idioma',                                           nl: 'Taal' },
    'wizard.ready.buttons_label':       { fr: 'Boutons actifs',                                         en: 'Active buttons',                                    es: 'Botones activos',                                  de: 'Aktive Schaltflächen',                             it: 'Pulsanti attivi',                                  pt: 'Botões ativos',                                    nl: 'Actieve knoppen' },

    // ===================== TOASTS =====================
    'toast.ready':                      { fr: 'Prêt.',                                                  en: 'Ready.',                                            es: 'Listo.',                                           de: 'Bereit.',                                          it: 'Pronto.',                                          pt: 'Pronto.',                                          nl: 'Klaar.' },
    'toast.cleared':                    { fr: 'Tout effacé.',                                           en: 'All cleared.',                                      es: 'Todo borrado.',                                    de: 'Alles gelöscht.',                                  it: 'Tutto cancellato.',                                pt: 'Tudo apagado.',                                    nl: 'Alles gewist.' },
    'toast.nothing_to_undo':            { fr: 'Rien à annuler.',                                        en: 'Nothing to undo.',                                  es: 'Nada que deshacer.',                               de: 'Nichts rückgängig zu machen.',                     it: 'Niente da annullare.',                             pt: 'Nada a desfazer.',                                 nl: 'Niets om ongedaan te maken.' },
    'toast.undone':                     { fr: 'Action annulée.',                                        en: 'Action undone.',                                    es: 'Acción deshecha.',                                 de: 'Aktion rückgängig gemacht.',                       it: 'Azione annullata.',                                pt: 'Ação desfeita.',                                   nl: 'Actie ongedaan gemaakt.' },
    'toast.element_added':              { fr: 'Élément ajouté à la demande #{n} : {label}',             en: 'Element added to request #{n}: {label}',            es: 'Elemento añadido a la solicitud #{n}: {label}',     de: 'Element zur Anfrage #{n} hinzugefügt: {label}',    it: 'Elemento aggiunto alla richiesta #{n}: {label}',   pt: 'Elemento adicionado à solicitação #{n}: {label}',  nl: 'Element toegevoegd aan verzoek #{n}: {label}' },
    'toast.ref_added':                  { fr: 'Référence ajoutée : {label}',                            en: 'Reference added: {label}',                          es: 'Referencia añadida: {label}',                      de: 'Referenz hinzugefügt: {label}',                    it: 'Riferimento aggiunto: {label}',                    pt: 'Referência adicionada: {label}',                   nl: 'Referentie toegevoegd: {label}' },
    'toast.ref_updated':                { fr: 'Référence #{n} mise à jour : {label}',                   en: 'Reference #{n} updated: {label}',                   es: 'Referencia #{n} actualizada: {label}',             de: 'Referenz #{n} aktualisiert: {label}',              it: 'Riferimento #{n} aggiornato: {label}',             pt: 'Referência #{n} atualizada: {label}',              nl: 'Referentie #{n} bijgewerkt: {label}' },
    'toast.errors_added_singular':      { fr: '{n} erreur ajoutée au segment courant.',                 en: '{n} error added to current segment.',               es: '{n} error añadido al segmento actual.',            de: '{n} Fehler zum aktuellen Segment hinzugefügt.',    it: '{n} errore aggiunto al segmento corrente.',        pt: '{n} erro adicionado ao segmento atual.',           nl: '{n} fout toegevoegd aan huidig segment.' },
    'toast.errors_added_plural':        { fr: '{n} erreurs ajoutées au segment courant.',               en: '{n} errors added to current segment.',              es: '{n} errores añadidos al segmento actual.',         de: '{n} Fehler zum aktuellen Segment hinzugefügt.',    it: '{n} errori aggiunti al segmento corrente.',        pt: '{n} erros adicionados ao segmento atual.',         nl: '{n} fouten toegevoegd aan huidig segment.' },
    'toast.no_errors':                  { fr: 'Aucune erreur détectée sur la page.',                    en: 'No errors detected on the page.',                   es: 'No se detectaron errores en la página.',           de: 'Keine Fehler auf der Seite erkannt.',              it: 'Nessun errore rilevato nella pagina.',             pt: 'Nenhum erro detectado na página.',                 nl: 'Geen fouten gedetecteerd op de pagina.' },
    'toast.tab_reloaded':               { fr: 'Onglet rechargé.',                                       en: 'Tab reloaded.',                                     es: 'Pestaña recargada.',                               de: 'Tab neu geladen.',                                 it: 'Scheda ricaricata.',                               pt: 'Aba recarregada.',                                 nl: 'Tabblad herladen.' },
    'toast.tab_reload_retry':           { fr: 'Onglet rechargé — réessaye dans 1 s.',                   en: 'Tab reloaded — retry in 1 s.',                      es: 'Pestaña recargada — reintenta en 1 s.',            de: 'Tab neu geladen — in 1 s erneut versuchen.',       it: 'Scheda ricaricata — riprova tra 1 s.',             pt: 'Aba recarregada — tente novamente em 1 s.',        nl: 'Tabblad herladen — probeer opnieuw in 1 s.' },
    'toast.tab_reload_fail':            { fr: 'Recharge KO : {err}',                                    en: 'Reload failed: {err}',                              es: 'Recarga falló: {err}',                             de: 'Neuladen fehlgeschlagen: {err}',                   it: 'Ricarica fallita: {err}',                          pt: 'Recarga falhou: {err}',                            nl: 'Herladen mislukt: {err}' },
    'toast.picker_fail':                { fr: 'Picker KO : {err}',                                      en: 'Picker failed: {err}',                              es: 'Selector falló: {err}',                            de: 'Auswahl fehlgeschlagen: {err}',                    it: 'Selettore fallito: {err}',                         pt: 'Seletor falhou: {err}',                            nl: 'Kiezer mislukt: {err}' },
    'toast.demande_deleted':            { fr: 'Demande #{n} supprimée.',                                en: 'Request #{n} deleted.',                             es: 'Solicitud #{n} eliminada.',                        de: 'Anfrage #{n} gelöscht.',                           it: 'Richiesta #{n} eliminata.',                        pt: 'Solicitação #{n} excluída.',                       nl: 'Verzoek #{n} verwijderd.' },
    'toast.session_started':            { fr: 'Session démarrée.',                                      en: 'Session started.',                                  es: 'Sesión iniciada.',                                 de: 'Sitzung gestartet.',                               it: 'Sessione avviata.',                                pt: 'Sessão iniciada.',                                 nl: 'Sessie gestart.' },
    'toast.session_stopped':            { fr: 'Session arrêtée — {n} demande(s) capturée(s).',          en: 'Session stopped — {n} request(s) captured.',        es: 'Sesión detenida — {n} solicitud(es) capturada(s).', de: 'Sitzung gestoppt — {n} Anfrage(n) erfasst.',       it: 'Sessione interrotta — {n} richiesta(e) catturata(e).', pt: 'Sessão parada — {n} solicitação(ões) capturada(s).', nl: 'Sessie gestopt — {n} verzoek(en) vastgelegd.' },
    'toast.demande_finalized':          { fr: 'Demande #{n} finalisée.',                                en: 'Request #{n} finalized.',                           es: 'Solicitud #{n} finalizada.',                       de: 'Anfrage #{n} abgeschlossen.',                      it: 'Richiesta #{n} finalizzata.',                      pt: 'Solicitação #{n} finalizada.',                     nl: 'Verzoek #{n} voltooid.' },
    'toast.nothing_to_finalize':        { fr: 'Rien à finaliser — parlez ou ajoutez une référence.',    en: 'Nothing to finalize — speak or add a reference.',   es: 'Nada que finalizar — habla o añade una referencia.', de: 'Nichts abzuschließen — sprich oder füge eine Referenz hinzu.', it: 'Niente da finalizzare — parla o aggiungi un riferimento.', pt: 'Nada a finalizar — fale ou adicione uma referência.', nl: 'Niets om te voltooien — spreek of voeg een referentie toe.' },
    'toast.edit_mode_entered':          { fr: "Édition de la demande #{n} — voix, picker, capture s'y insèrent.", en: 'Editing request #{n} — voice, picker, capture insert here.', es: 'Editando solicitud #{n} — voz, selector y captura se insertan aquí.', de: 'Bearbeite Anfrage #{n} — Stimme, Auswahl, Aufnahme fügen sich hier ein.', it: 'Modifica richiesta #{n} — voce, selettore, cattura inseriti qui.', pt: 'Editando solicitação #{n} — voz, seletor, captura inseridos aqui.', nl: 'Verzoek #{n} bewerken — stem, kiezer, opname worden hier ingevoegd.' },
    'toast.edit_mode_exited':           { fr: 'Mode édition terminé.',                                  en: 'Edit mode exited.',                                 es: 'Modo edición terminado.',                          de: 'Bearbeitungsmodus beendet.',                       it: 'Modalità modifica terminata.',                     pt: 'Modo edição encerrado.',                           nl: 'Bewerkmodus beëindigd.' },
    'toast.shot_running':               { fr: 'Capture ({mode})…',                                      en: 'Capture ({mode})…',                                 es: 'Captura ({mode})…',                                de: 'Aufnahme ({mode})…',                               it: 'Cattura ({mode})…',                                pt: 'Captura ({mode})…',                                nl: 'Opname ({mode})…' },
    'toast.shot_fail':                  { fr: 'Capture KO : {err}',                                     en: 'Capture failed: {err}',                             es: 'Captura falló: {err}',                             de: 'Aufnahme fehlgeschlagen: {err}',                   it: 'Cattura fallita: {err}',                           pt: 'Captura falhou: {err}',                            nl: 'Opname mislukt: {err}' },
    'toast.shot_added':                 { fr: 'Capture {mode} ajoutée à la demande #{n}',               en: '{mode} capture added to request #{n}',              es: 'Captura {mode} añadida a la solicitud #{n}',       de: 'Aufnahme {mode} zu Anfrage #{n} hinzugefügt',      it: 'Cattura {mode} aggiunta alla richiesta #{n}',      pt: 'Captura {mode} adicionada à solicitação #{n}',     nl: 'Opname {mode} toegevoegd aan verzoek #{n}' },
    'toast.shot_added_current':         { fr: 'Capture {mode} OK — ajoutée comme référence',            en: '{mode} capture OK — added as reference',            es: 'Captura {mode} OK — añadida como referencia',      de: '{mode}-Aufnahme OK — als Referenz hinzugefügt',    it: 'Cattura {mode} OK — aggiunta come riferimento',    pt: 'Captura {mode} OK — adicionada como referência',   nl: '{mode}-opname OK — toegevoegd als referentie' },
    'toast.merge_complete':             { fr: 'Demandes fusionnées dans #{n}.',                         en: 'Requests merged into #{n}.',                        es: 'Solicitudes fusionadas en #{n}.',                  de: 'Anfragen in #{n} zusammengeführt.',                it: 'Richieste unite in #{n}.',                         pt: 'Solicitações mescladas em #{n}.',                  nl: 'Verzoeken samengevoegd in #{n}.' },
    'toast.annotate_open':              { fr: "Annotateur ouvert dans l'onglet actif…",                 en: 'Annotator opened in the active tab…',               es: 'Anotador abierto en la pestaña activa…',           de: 'Annotator im aktiven Tab geöffnet…',               it: 'Annotatore aperto nella scheda attiva…',           pt: 'Anotador aberto na aba ativa…',                    nl: 'Annotator geopend in actief tabblad…' },
    'toast.annotate_cancelled':         { fr: 'Annotation annulée.',                                    en: 'Annotation cancelled.',                             es: 'Anotación cancelada.',                             de: 'Anmerkung abgebrochen.',                           it: 'Annotazione annullata.',                           pt: 'Anotação cancelada.',                              nl: 'Annotatie geannuleerd.' },
    'toast.annotate_fail':              { fr: 'Annotation KO : {err}',                                  en: 'Annotation failed: {err}',                          es: 'Anotación falló: {err}',                           de: 'Anmerkung fehlgeschlagen: {err}',                  it: 'Annotazione fallita: {err}',                       pt: 'Anotação falhou: {err}',                           nl: 'Annotatie mislukt: {err}' },
    'toast.annotate_saved':             { fr: 'Référence #{n} : annotation enregistrée.',               en: 'Reference #{n}: annotation saved.',                 es: 'Referencia #{n}: anotación guardada.',             de: 'Referenz #{n}: Anmerkung gespeichert.',            it: 'Riferimento #{n}: annotazione salvata.',           pt: 'Referência #{n}: anotação salva.',                 nl: 'Referentie #{n}: annotatie opgeslagen.' },
    'toast.annotate_unavailable':       { fr: 'Capture indisponible (cache local).',                    en: 'Capture unavailable (local cache).',                es: 'Captura no disponible (caché local).',             de: 'Aufnahme nicht verfügbar (lokaler Cache).',        it: 'Cattura non disponibile (cache locale).',          pt: 'Captura indisponível (cache local).',              nl: 'Opname niet beschikbaar (lokale cache).' },
    'toast.replace_ref_prompt':         { fr: 'Cliquez un élément pour remplacer la référence #{n}…',   en: 'Click an element to replace reference #{n}…',       es: 'Haz clic en un elemento para reemplazar la referencia #{n}…', de: 'Klicke auf ein Element, um Referenz #{n} zu ersetzen…', it: 'Fai clic su un elemento per sostituire il riferimento #{n}…', pt: 'Clique em um elemento para substituir a referência #{n}…', nl: 'Klik op een element om referentie #{n} te vervangen…' },
    'toast.text_selection_added':       { fr: 'Sélection texte ajoutée au segment courant.',            en: 'Text selection added to current segment.',          es: 'Selección de texto añadida al segmento actual.',   de: 'Textauswahl zum aktuellen Segment hinzugefügt.',   it: 'Selezione di testo aggiunta al segmento corrente.', pt: 'Seleção de texto adicionada ao segmento atual.',   nl: 'Tekstselectie toegevoegd aan huidig segment.' },
    'toast.image_downloading':          { fr: "Téléchargement de l'image…",                             en: 'Downloading image…',                                es: 'Descargando imagen…',                              de: 'Bild wird heruntergeladen…',                       it: 'Download immagine…',                               pt: 'Baixando imagem…',                                 nl: 'Afbeelding downloaden…' },
    'toast.image_added':                { fr: 'Image ajoutée comme référence.',                         en: 'Image added as reference.',                         es: 'Imagen añadida como referencia.',                  de: 'Bild als Referenz hinzugefügt.',                   it: 'Immagine aggiunta come riferimento.',              pt: 'Imagem adicionada como referência.',               nl: 'Afbeelding toegevoegd als referentie.' },
    'toast.image_added_url':            { fr: 'Image ajoutée (URL seulement).',                         en: 'Image added (URL only).',                           es: 'Imagen añadida (solo URL).',                       de: 'Bild hinzugefügt (nur URL).',                      it: 'Immagine aggiunta (solo URL).',                    pt: 'Imagem adicionada (somente URL).',                 nl: 'Afbeelding toegevoegd (alleen URL).' },
    'toast.images_added_singular':      { fr: '{n} image ajoutée comme référence.',                     en: '{n} image added as reference.',                     es: '{n} imagen añadida como referencia.',              de: '{n} Bild als Referenz hinzugefügt.',               it: '{n} immagine aggiunta come riferimento.',          pt: '{n} imagem adicionada como referência.',           nl: '{n} afbeelding toegevoegd als referentie.' },
    'toast.images_added_plural':        { fr: '{n} images ajoutées comme références.',                  en: '{n} images added as references.',                   es: '{n} imágenes añadidas como referencias.',          de: '{n} Bilder als Referenzen hinzugefügt.',           it: '{n} immagini aggiunte come riferimenti.',          pt: '{n} imagens adicionadas como referências.',        nl: '{n} afbeeldingen toegevoegd als referenties.' },
    'toast.copy_paste_into':            { fr: 'Prompt copié — collez-le dans {name}',                   en: 'Prompt copied — paste it into {name}',              es: 'Prompt copiado — pégalo en {name}',                de: 'Prompt kopiert — füge ihn in {name} ein',          it: 'Prompt copiato — incollalo in {name}',             pt: 'Prompt copiado — cole em {name}',                  nl: 'Prompt gekopieerd — plak het in {name}' },
    'toast.copy_paste_full':            { fr: 'Prompt copié — collez dans Claude Code et drag-droppez les screenshots.', en: 'Prompt copied — paste into Claude Code and drag-drop the screenshots.', es: 'Prompt copiado — pégalo en Claude Code y arrastra las capturas.', de: 'Prompt kopiert — in Claude Code einfügen und Screenshots per Drag & Drop hinzufügen.', it: 'Prompt copiato — incolla in Claude Code e trascina gli screenshot.', pt: 'Prompt copiado — cole no Claude Code e arraste as capturas.', nl: 'Prompt gekopieerd — plak in Claude Code en sleep de schermafbeeldingen.' },
    'toast.copied_demande':             { fr: 'Prompt de la demande #{n} copié.',                       en: 'Prompt of request #{n} copied.',                    es: 'Prompt de la solicitud #{n} copiado.',             de: 'Prompt der Anfrage #{n} kopiert.',                 it: 'Prompt della richiesta #{n} copiato.',             pt: 'Prompt da solicitação #{n} copiado.',              nl: 'Prompt van verzoek #{n} gekopieerd.' },
    'toast.copy_fail':                  { fr: 'Copie impossible : {err}',                               en: 'Copy failed: {err}',                                es: 'Copia falló: {err}',                               de: 'Kopieren fehlgeschlagen: {err}',                   it: 'Copia fallita: {err}',                             pt: 'Cópia falhou: {err}',                              nl: 'Kopiëren mislukt: {err}' },
    'toast.nothing_to_download':        { fr: 'Rien à télécharger.',                                    en: 'Nothing to download.',                              es: 'Nada que descargar.',                              de: 'Nichts zum Herunterladen.',                        it: 'Niente da scaricare.',                             pt: 'Nada para baixar.',                                nl: 'Niets om te downloaden.' },
    'toast.bundle_downloaded':          { fr: 'Prompt + {n} capture(s) téléchargés.',                   en: 'Prompt + {n} screenshot(s) downloaded.',            es: 'Prompt + {n} captura(s) descargados.',             de: 'Prompt + {n} Screenshot(s) heruntergeladen.',      it: 'Prompt + {n} screenshot scaricati.',               pt: 'Prompt + {n} captura(s) baixados.',                nl: 'Prompt + {n} schermafbeelding(en) gedownload.' },
    'toast.demande_downloaded':         { fr: 'Demande #{n} téléchargée.',                              en: 'Request #{n} downloaded.',                          es: 'Solicitud #{n} descargada.',                       de: 'Anfrage #{n} heruntergeladen.',                    it: 'Richiesta #{n} scaricata.',                        pt: 'Solicitação #{n} baixada.',                        nl: 'Verzoek #{n} gedownload.' },
    'toast.demande_downloaded_with':    { fr: 'Demande #{n} téléchargée (+ {imgs} capture(s)).',        en: 'Request #{n} downloaded (+ {imgs} screenshot(s)).', es: 'Solicitud #{n} descargada (+ {imgs} captura(s)).', de: 'Anfrage #{n} heruntergeladen (+ {imgs} Screenshot(s)).', it: 'Richiesta #{n} scaricata (+ {imgs} screenshot).',  pt: 'Solicitação #{n} baixada (+ {imgs} captura(s)).',  nl: 'Verzoek #{n} gedownload (+ {imgs} schermafbeelding(en)).' },
    'toast.bridge_connecting':          { fr: 'Connexion au bridge {label}…',                           en: 'Connecting to {label} bridge…',                     es: 'Conectando al bridge {label}…',                    de: 'Verbinde mit {label}-Bridge…',                     it: 'Connessione al bridge {label}…',                   pt: 'Conectando ao bridge {label}…',                    nl: 'Verbinden met {label}-bridge…' },
    'toast.bridge_offline':             { fr: "Bridge VS Code introuvable (port {port}). Installez l'extension BIAIF dans VS Code.", en: 'VS Code bridge not found (port {port}). Install the BIAIF extension in VS Code.', es: 'Bridge VS Code no encontrado (puerto {port}). Instala la extensión BIAIF en VS Code.', de: 'VS Code-Bridge nicht gefunden (Port {port}). Installiere die BIAIF-Erweiterung in VS Code.', it: 'Bridge VS Code non trovato (porta {port}). Installa l\'estensione BIAIF in VS Code.', pt: 'Bridge VS Code não encontrado (porta {port}). Instale a extensão BIAIF no VS Code.', nl: 'VS Code-bridge niet gevonden (poort {port}). Installeer de BIAIF-extensie in VS Code.' },
    'toast.bridge_sent':                { fr: 'Demande #{n} → {label}{imgs}.',                          en: 'Request #{n} → {label}{imgs}.',                     es: 'Solicitud #{n} → {label}{imgs}.',                  de: 'Anfrage #{n} → {label}{imgs}.',                    it: 'Richiesta #{n} → {label}{imgs}.',                  pt: 'Solicitação #{n} → {label}{imgs}.',                nl: 'Verzoek #{n} → {label}{imgs}.' },
    'toast.bridge_fail':                { fr: 'Erreur {label} bridge : {err}',                          en: '{label} bridge error: {err}',                       es: 'Error de bridge {label}: {err}',                   de: '{label}-Bridge-Fehler: {err}',                     it: 'Errore bridge {label}: {err}',                     pt: 'Erro de bridge {label}: {err}',                    nl: '{label}-bridge fout: {err}' },
    'toast.nothing_to_send':            { fr: 'Rien à envoyer pour cette demande.',                     en: 'Nothing to send for this request.',                 es: 'Nada que enviar para esta solicitud.',             de: 'Nichts zu senden für diese Anfrage.',              it: 'Niente da inviare per questa richiesta.',          pt: 'Nada a enviar para esta solicitação.',             nl: 'Niets te verzenden voor dit verzoek.' },
    'toast.nothing_to_inject':          { fr: 'Rien à injecter dans cette demande.',                    en: 'Nothing to inject in this request.',                es: 'Nada que inyectar en esta solicitud.',             de: 'Nichts zu injizieren in dieser Anfrage.',          it: 'Niente da iniettare in questa richiesta.',         pt: 'Nada a injetar nesta solicitação.',                nl: 'Niets te injecteren in dit verzoek.' },
    'toast.injecting':                  { fr: "Injection en cours dans l'éditeur Claude Code…",         en: 'Injecting into Claude Code editor…',                es: 'Inyectando en el editor Claude Code…',             de: 'Injiziere in Claude Code-Editor…',                 it: 'Iniezione nell\'editor Claude Code…',              pt: 'Injetando no editor Claude Code…',                 nl: 'Injecteren in Claude Code-editor…' },
    'toast.inject_fail':                { fr: "Injection impossible : {err} — assurez-vous d'être sur l'onglet Claude Code.", en: 'Injection failed: {err} — make sure you are on the Claude Code tab.', es: 'Inyección falló: {err} — asegúrate de estar en la pestaña Claude Code.', de: 'Injektion fehlgeschlagen: {err} — Stelle sicher, dass du auf dem Claude Code-Tab bist.', it: 'Iniezione fallita: {err} — assicurati di essere sulla scheda Claude Code.', pt: 'Injeção falhou: {err} — certifique-se de estar na aba Claude Code.', nl: 'Injectie mislukt: {err} — zorg dat je op het Claude Code-tabblad bent.' },
    'toast.inject_fail_generic':        { fr: 'Injection échouée : {err}',                              en: 'Injection failed: {err}',                           es: 'Inyección falló: {err}',                           de: 'Injektion fehlgeschlagen: {err}',                  it: 'Iniezione fallita: {err}',                         pt: 'Injeção falhou: {err}',                            nl: 'Injectie mislukt: {err}' },
    'toast.injected':                   { fr: 'Demande #{n} injectée{imgs}.',                           en: 'Request #{n} injected{imgs}.',                      es: 'Solicitud #{n} inyectada{imgs}.',                  de: 'Anfrage #{n} injiziert{imgs}.',                    it: 'Richiesta #{n} iniettata{imgs}.',                  pt: 'Solicitação #{n} injetada{imgs}.',                 nl: 'Verzoek #{n} geïnjecteerd{imgs}.' },
    'toast.storage_warning':            { fr: "Stockage presque plein ({mb} MB). Videz l'historique pour libérer de l'espace.", en: 'Storage almost full ({mb} MB). Clear history to free space.', es: 'Almacenamiento casi lleno ({mb} MB). Vacía el historial para liberar espacio.', de: 'Speicher fast voll ({mb} MB). Verlauf leeren, um Platz zu schaffen.', it: 'Spazio quasi pieno ({mb} MB). Svuota la cronologia per liberare spazio.', pt: 'Armazenamento quase cheio ({mb} MB). Limpe o histórico para liberar espaço.', nl: 'Opslag bijna vol ({mb} MB). Wis geschiedenis om ruimte vrij te maken.' },

    // ===== Mic =====
    'mic.test_running':                 { fr: 'Test micro en cours — parle pour voir le niveau.',       en: 'Mic test running — speak to see the level.',        es: 'Test de micrófono en curso — habla para ver el nivel.', de: 'Mikrofontest läuft — sprich, um den Pegel zu sehen.', it: 'Test microfono in corso — parla per vedere il livello.', pt: 'Teste de microfone em andamento — fale para ver o nível.', nl: 'Microfoontest actief — spreek om het niveau te zien.' },
    'mic.test_fail':                    { fr: 'Test micro KO : {err}',                                  en: 'Mic test failed: {err}',                            es: 'Test de micrófono falló: {err}',                   de: 'Mikrofontest fehlgeschlagen: {err}',               it: 'Test microfono fallito: {err}',                    pt: 'Teste de microfone falhou: {err}',                 nl: 'Microfoontest mislukt: {err}' },
    'mic.test_btn_default':             { fr: '🔊 Tester',                                              en: '🔊 Test',                                           es: '🔊 Probar',                                        de: '🔊 Testen',                                        it: '🔊 Testa',                                         pt: '🔊 Testar',                                        nl: '🔊 Testen' },
    'mic.test_btn_stop':                { fr: '⏹ Stop test',                                            en: '⏹ Stop test',                                       es: '⏹ Detener test',                                   de: '⏹ Test stoppen',                                   it: '⏹ Stop test',                                      pt: '⏹ Parar teste',                                    nl: '⏹ Stop test' },
    'mic.error_prefix':                 { fr: 'Micro : {err}',                                          en: 'Mic: {err}',                                        es: 'Micrófono: {err}',                                 de: 'Mikrofon: {err}',                                  it: 'Microfono: {err}',                                 pt: 'Microfone: {err}',                                 nl: 'Microfoon: {err}' },
    'mic.idle_warning':                 { fr: 'Aucun signal audio depuis 12 s — vérifiez le micro par défaut dans Chrome.', en: 'No audio signal for 12 s — check default mic in Chrome.', es: 'Sin señal de audio durante 12 s — comprueba el micro predeterminado en Chrome.', de: 'Kein Audiosignal seit 12 s — prüfe den Standard-Mikrofon in Chrome.', it: 'Nessun segnale audio da 12 s — verifica il microfono predefinito in Chrome.', pt: 'Sem sinal de áudio por 12 s — verifique o microfone padrão no Chrome.', nl: 'Geen audiosignaal sinds 12 s — controleer de standaard microfoon in Chrome.' },
    'mic.label_active':                 { fr: 'Micro ✓',                                                en: 'Mic ✓',                                             es: 'Micro ✓',                                          de: 'Mikro ✓',                                          it: 'Micro ✓',                                          pt: 'Micro ✓',                                          nl: 'Micro ✓' },
    'mic.err.denied':                   { fr: "micro bloqué pour BIAIF — clique ici pour ouvrir la page de permissions de l'extension", en: 'mic blocked for BIAIF — click here to open the extension permissions page', es: 'micrófono bloqueado para BIAIF — haz clic aquí para abrir los permisos', de: 'Mikrofon für BIAIF blockiert — hier klicken zum Öffnen der Berechtigungen', it: 'microfono bloccato per BIAIF — clicca qui per aprire le autorizzazioni', pt: 'microfone bloqueado para BIAIF — clique aqui para abrir as permissões', nl: 'microfoon geblokkeerd voor BIAIF — klik hier om machtigingen te openen' },
    'mic.err.no_speech':                { fr: 'rien entendu',                                           en: 'nothing heard',                                     es: 'no se oyó nada',                                   de: 'nichts gehört',                                    it: 'nulla udito',                                      pt: 'nada ouvido',                                      nl: 'niets gehoord' },
    'mic.err.audio_capture':            { fr: 'aucun micro détecté',                                    en: 'no mic detected',                                   es: 'no se detectó micrófono',                          de: 'kein Mikrofon erkannt',                            it: 'nessun microfono rilevato',                        pt: 'nenhum microfone detectado',                       nl: 'geen microfoon gedetecteerd' },
    'mic.err.network':                  { fr: 'erreur réseau',                                          en: 'network error',                                     es: 'error de red',                                     de: 'Netzwerkfehler',                                   it: 'errore di rete',                                   pt: 'erro de rede',                                     nl: 'netwerkfout' },
    'mic.err.aborted':                  { fr: 'reconnaissance interrompue',                             en: 'recognition aborted',                               es: 'reconocimiento interrumpido',                      de: 'Erkennung abgebrochen',                            it: 'riconoscimento interrotto',                        pt: 'reconhecimento interrompido',                      nl: 'herkenning afgebroken' },
    'mic.err.lang_unsupported':         { fr: 'langue non supportée',                                   en: 'language not supported',                            es: 'idioma no soportado',                              de: 'Sprache nicht unterstützt',                        it: 'lingua non supportata',                            pt: 'idioma não suportado',                             nl: 'taal niet ondersteund' },
    'mic.err.bad_grammar':              { fr: 'grammaire invalide',                                     en: 'invalid grammar',                                   es: 'gramática inválida',                               de: 'ungültige Grammatik',                              it: 'grammatica non valida',                            pt: 'gramática inválida',                               nl: 'ongeldige grammatica' },
    'mic.err.auto_restart':             { fr: 'session coupée par le navigateur — recliquez sur le micro', en: 'session cut by browser — click the mic again',     es: 'sesión cortada por el navegador — vuelve a hacer clic en el micrófono', de: 'Sitzung vom Browser unterbrochen — Mikrofon erneut anklicken', it: 'sessione interrotta dal browser — riclicca sul microfono', pt: 'sessão cortada pelo navegador — clique no microfone novamente', nl: 'sessie afgesneden door browser — klik opnieuw op de microfoon' },
    'mic.err.no_media':                 { fr: 'API media non disponible',                               en: 'media API unavailable',                             es: 'API media no disponible',                          de: 'Media-API nicht verfügbar',                        it: 'API media non disponibile',                        pt: 'API de mídia indisponível',                        nl: 'media-API niet beschikbaar' },
    'mic.err.not_supported':            { fr: 'reconnaissance vocale non supportée par le navigateur',  en: 'voice recognition not supported by browser',        es: 'reconocimiento de voz no soportado por el navegador', de: 'Spracherkennung vom Browser nicht unterstützt',    it: 'riconoscimento vocale non supportato dal browser', pt: 'reconhecimento de voz não suportado pelo navegador', nl: 'spraakherkenning niet ondersteund door browser' },
    'mic.err.init_failed':              { fr: 'initialisation impossible',                              en: 'initialization failed',                             es: 'inicialización falló',                             de: 'Initialisierung fehlgeschlagen',                   it: 'inizializzazione fallita',                         pt: 'inicialização falhou',                             nl: 'initialisatie mislukt' },
    'mic.err.start_failed':             { fr: 'impossible de démarrer le micro',                        en: 'unable to start mic',                               es: 'no se puede iniciar el micrófono',                 de: 'Mikrofon kann nicht gestartet werden',             it: 'impossibile avviare il microfono',                 pt: 'não foi possível iniciar o microfone',             nl: 'kan microfoon niet starten' },

    // ===== Confirms =====
    'confirm.delete_demande':           { fr: 'Supprimer la demande #{n} ?\n\n{preview}',               en: 'Delete request #{n}?\n\n{preview}',                 es: '¿Eliminar la solicitud #{n}?\n\n{preview}',        de: 'Anfrage #{n} löschen?\n\n{preview}',               it: 'Eliminare la richiesta #{n}?\n\n{preview}',        pt: 'Excluir a solicitação #{n}?\n\n{preview}',         nl: 'Verzoek #{n} verwijderen?\n\n{preview}' },
    'confirm.clear_all':                { fr: 'Effacer la session ? (Toutes les demandes finalisées et la demande en cours seront perdues)', en: 'Clear session? (All finalized requests and the current request will be lost)', es: '¿Vaciar la sesión? (Se perderán todas las solicitudes finalizadas y la actual)', de: 'Sitzung löschen? (Alle abgeschlossenen und die aktuelle Anfrage gehen verloren)', it: 'Svuotare la sessione? (Tutte le richieste finalizzate e quella corrente saranno perse)', pt: 'Limpar a sessão? (Todas as solicitações finalizadas e a atual serão perdidas)', nl: 'Sessie wissen? (Alle voltooide en huidige verzoeken gaan verloren)' },

    // ===== Aria/labels =====
    'aria.delete_demande':              { fr: "Supprimer la demande {n}",                               en: 'Delete request {n}',                                es: 'Eliminar solicitud {n}',                           de: 'Anfrage {n} löschen',                              it: 'Elimina richiesta {n}',                            pt: 'Excluir solicitação {n}',                          nl: 'Verzoek {n} verwijderen' },
    'aria.demande_text':                { fr: "Texte de la demande {n}",                                en: 'Request {n} text',                                  es: 'Texto de la solicitud {n}',                        de: 'Text der Anfrage {n}',                             it: 'Testo della richiesta {n}',                        pt: 'Texto da solicitação {n}',                         nl: 'Tekst van verzoek {n}' },
    'aria.errors_count':                { fr: 'Erreurs console ({n})',                                  en: 'Console errors ({n})',                              es: 'Errores de consola ({n})',                         de: 'Konsolenfehler ({n})',                             it: 'Errori console ({n})',                             pt: 'Erros do console ({n})',                           nl: 'Consolefouten ({n})' },
    'aria.open_in_new_tab':             { fr: 'Ouvrir {name} dans un nouvel onglet et copier le prompt', en: 'Open {name} in a new tab and copy the prompt',     es: 'Abrir {name} en una pestaña y copiar el prompt',   de: '{name} in neuem Tab öffnen und Prompt kopieren',   it: 'Apri {name} in una nuova scheda e copia il prompt', pt: 'Abrir {name} em nova aba e copiar o prompt',       nl: '{name} in nieuw tabblad openen en prompt kopiëren' },
  };

  // ── API ─────────────────────────────────────────────────────────────────────

  function _format(s, vars) {
    if (!vars) return s;
    return s.replace(/\{([a-zA-Z0-9_]+)\}/g, function (_, k) {
      return (vars[k] !== undefined && vars[k] !== null) ? String(vars[k]) : '';
    });
  }

  function t(key, vars) {
    var entry = TRANSLATIONS[key];
    if (!entry) return _format(key, vars);
    var raw = entry[_lang] || entry['fr'] || key;
    return _format(raw, vars);
  }

  function getLang() {
    return _lang;
  }

  function detectBrowserLang() {
    var nav = (navigator.language || navigator.userLanguage || 'fr').toLowerCase();
    var base = nav.split('-')[0];
    if (SUPPORTED.indexOf(base) !== -1) return base;
    return 'fr';
  }

  function setLang(lang) {
    if (SUPPORTED.indexOf(lang) === -1) lang = 'fr';
    _lang = lang;
    document.documentElement.setAttribute('lang', lang);
    var grid = document.getElementById('sp-lang-grid');
    if (grid) {
      grid.querySelectorAll('[data-lang]').forEach(function (btn) {
        btn.classList.toggle('is-active', btn.dataset.lang === lang);
      });
    }
    applyDOM();
  }

  function applyDOM() {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (key) el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (key) el.innerHTML = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder');
      if (key) el.setAttribute('placeholder', t(key));
    });
  }

  // ── Export ──────────────────────────────────────────────────────────────────
  window.BIAIFi18n = {
    t: t,
    getLang: getLang,
    setLang: setLang,
    applyDOM: applyDOM,
    detectBrowserLang: detectBrowserLang,
  };

})(window);
